vuejs/vuepress

lib/prepare.js

According to the docs, to use a custom layout, I should create a .vuepress/theme directory in your docs root, and then create a Layout.vue file.
But vuepress throws an error, when I follow this instruction.
I found the`themeDir`  should be `path.resolve(vuepressDir, 'theme')`, which would be `/.vuepress/theme`, instead of `path.resolve(sourceDir, 'theme')`, which would be `/theme/`

fix: fix vuepress cant resolve custom theme under .vuepress/theme

---

lib/markdown/link.js

Updating `rel="noopener noreferrer"` for Edge and (partial) IE11 support:
https://caniuse.com/#search=noopener 
https://caniuse.com/#search=noreferrer
Reason here: https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/

Update link.js 

---

lib/prepare.js

If vuepress is run in the root of a npm package
(eg. `vuepress build .`), it would include all markdown files from
the `node_modules` folder, which breaks the build process.
Maybe this setting should be customizable via `.vuepress/config.js`, so users can exclude other files/folders.

Don't include files from node_modules

---

lib/default-theme/styles/theme.styl

The CSS rule `&:nth-child(2)` only highlights the second table row.
This change will highlight every second table row, which improves
readability.

Highlight every second table row

---

lib/prepare.js

Until now, only `README.md` files got treated as a directory index.
This commit also allows `index.md` to be used as index files.
Related to #17.

Allow index.md files as index pages

---

lib/default-theme/styles/code.styl

That margin was creating horizontal scroll when it wasn't necessary
this removes the horizontal extra width, removing the scrollbar with it

fix(style): prevent scrollbar in code

---

docs/guide/markdown.md

Let me know if you prefer [GitHub URL](https://github.com/markdown-it/markdown-it).
`git grep "]()"` doesn't show anything else, by the way.

Missing link in document

---

bin/vuepress.js
docs/README.md
docs/guide/getting-started.md

As in #8 targetDir parameter of `dev` and `build` commands are optional and defaults to cwd.

Commands now defaults targetDir to cwd.

---

lib/build.js
package.json
yarn.lock

example.md
```yaml
meta:
- foo: how to "broke" bar
```
before patch:
```html
<meta foo="how to "broke" bar">
```
after patch:
```html
<meta foo="how to &quot;broke&quot; bar">
````

Added escaping of meta tag attribute value

---

README.md

Since vuepress uses yarn instead of npm, so it's better to recommend contributors to use yarn instead of generating npm's locked file.

Update dev instruction to yarn

---

lib/default-theme/styles/theme.styl

Auto overflow makes the empty scrollbar disappear when it's not needed but shown when there's not enough vertical space to display all items.

[Default Theme] [Sidebar] Overflow-y auto

---

lib/default-theme/NavLinks.vue

so if i add a home route as follows
the home link remains active even I am at a different page

Fix home link '/' shouldn’t always stays active

---

lib/default-theme/styles/theme.styl

This PR adds minimal styling to `<kbd>` elements as a start.
Before:
After:

add <kbd> styles

---

README.md
docs/README.md

I have found that many users will encounter some unexpected errors caused by the wrong version of the Node.js, see:
- #21 
- #39 
- #51
- #63 
Although we have set minimum version at `engines` field of `package.json`, but NPM still existed some issues for that, See: https://github.com/npm/npm/issues/12486 
Of course, we can also check the node version at runtime, but it would be better to point out in the document that the **user can avoid these problems in advance**.

DOC - Add node version warning.

---

docs/default-theme-config/README.md
docs/guide/custom-themes.md

When I was translating the Chinese document, I found a problem: The expression of `YAML front matter` may be a bit inconsistent:
- `YAML frontmatter`
- `YAML front matter`
- `front matter`
After referring to https://jekyllrb.com/docs/frontmatter/, I fount that there should be space between word `front` and `matter`.
And on some frequently appearing pages, there is no any place where I can click to goto the details.
So this PR is a little tweaks for docs.

DOC - add at least one reference link for YAML front matter at each page.

---

lib/webpack/createBaseConfig.js

```bash
ERROR in ./node_modules/vuepress/lib/app/app.js
Module parse failed: Unexpected token (76:11)
You may need an appropriate loader to handle this file type.
|   })
|
|   return { ...{ app, router }}
| }
|
@ ./node_modules/vuepress/lib/app/clientEntry.js 4:0-33 7:24-33
@ multi ./node_modules/vuepress/lib/app/clientEntry.js
```
Not sure why others didn't get this error, fixed by including `lib` in `js` rule.
Besides, if `siteConfig.evergreen` is enabled it will also throw this error since webpack can't parse object rest spreading for now.
Time to switch to Babel or use es2015-only features?

Always transpile lib directory

---

lib/app/app.js
lib/prepare.js

.vuepress/inject.js:
```js
import Element from 'element-ui'
export default ({ Vue, app, router }) => {
Vue.use(Element)
}
```
readme.md:
```md
<el-button>.....</el-button>
```

Allow injecting Vue, app, router

---

docs/guide/deploy.md

I was a bit confused when deploying according to the guide.
So I think it would be better to use the same script name.
```
{
"scripts": {
"docs:dev": "vuepress dev docs",
"docs:build": "vuepress build docs"
}
}
```
```
{
"scripts": {
"build-docs": "vuepress build docs"
}
}
```

docs: unify deploy script name

---

lib/prepare.js

The latest commit broke path resolution for not-found pages in (local) custom themes: https://github.com/vuejs/vuepress/commit/72e5666161675e22c74ebcbcd5034534bdea9f58#diff-a51476be0f7d46d12aa959f6343012ccR67
With this commit, not-found pages are found again. :octocat:

Correctly resolve not-found path

---

bin/vuepress.js

**Current behavior**
$ vuepress build --dest ./public site/content
Rendering static HTML...
Success! Generated static files in site/content/**.vuepress/dist**.
**Expected behavior**
$ vuepress build --dest ./public site/content
Rendering static HTML...
Success! Generated static files in **public**.

Fix for build destination path

---

docs/.vuepress/config.yml
lib/prepare.js
package.json
yarn.lock

Add support yaml config format

feat:support yaml config

---

lib/util/index.js

This fixes an issue concerning missing slug link of sidebar.
The issue can even be reproduced in the official VuePress guide.
1. Access https://vuepress.vuejs.org/guide/
2. Click the `Why Not ...?` link in sidebar
We can see that the guide page doesn't scroll to the `Why Not ...?` header.
The issue is caused by markdown-it's `typographer: true` option, which is for beautification. By the option, three dots (`...`) are replaced with a single unicode character `…`. They are handled differently by [slugify()](https://github.com/vuejs/vuepress/blob/master/lib/markdown/slugify.js).
When logging the tokens, `tokens[i + 1].content` is not `typographer`-ed, even its actual slug is.
The token already has an attribute `id` which is a correct and final result of the parser. Also, the slug is used …

Use header's slug as it is if possible

---

lib/default-theme/styles/theme.styl

This adds some styling to the hr element which is produced when you have
`---` in markdown on a line on its own. This makes the element look like
all other border elements `1px`, of `$borderColor`.
Before (`<hr>` then border):
After:

tweak(default-theme): Adds hr element style

---

lib/default-theme/Sidebar.vue

- Version: 0.6.0
- Description: The bottom gutter of sidebar in mobile is too small (=0).

Enhance the sidebar's bottom gutter.

---

lib/default-theme/Layout.vue
lib/default-theme/styles/theme.styl

- Version: 0.6.0
- Description: As a mobile user, I often open the sidebar but didn't make any choices, so it would be good to allow me to check the part outside sidebar to close the sidebar.

Support click the part outside sidebar to close the sidebar

---

docs/.vuepress/config.js
lib/default-theme/DropdownLink.vue
lib/default-theme/DropdownTransition.vue
lib/default-theme/SidebarGroup.vue
lib/default-theme/styles/arrow.styl
lib/default-theme/styles/config.styl

- Version: 0.6.0
- Description: The navbar's dropdown should leverage the same transition from sidebar. and the arrow's style also should keep consistent.

Ensure that all the dropdown's style are consistent

---

.gitignore
docs/default-theme-config/README.md
lib/default-theme/NavLinks.vue

Changing repo label depending on the host

---

lib/default-theme/styles/code.styl

AFAIK, `none` isn't a valid `background-color` value. I changed it to `transparent`. This also resulted the line to match with the rest of the background color on the code block.
This is how it used to look like with `background-color` set to `none`:
As you can see, it had slightly different background color.

Fix invalid `background-color` value from code block

---

docs/guide/using-vue.md
docs/zh/guide/using-vue.md
lib/webpack/createBaseConfig.js

- Version: 0.7.0
- Description: Fixed for #146

Support built-in pug config and document using pro-processors at component

---

docs/guide/custom-themes.md
lib/app/app.js
lib/prepare.js

Adds support for loading index.js in themes.
This works in the same way that `.vuepress/enhanceApp.js` works but for themes instead, allowing theme designers to extend the vue app in more useful ways.
This should help with creating custom themes for things like blogging sites like requested in #36

Theme index enhancment support

---

docs/default-theme-config/README.md
docs/zh/default-theme-config/README.md
lib/default-theme/Page.vue

In some cases, project and doc are not in the same repo like Vue. So, and a `docsRepo` option  in config file to distinguish project and doc address.

feat: Add docsRepo

---

docs/config/README.md
docs/zh/config/README.md
lib/webpack/createBaseConfig.js

feat: expose all css pre-processor's options. (close #169)

---

docs/guide/markdown.md

When I was first getting setup with Vuepress, I found it a little confusing on how to link out to the relative markdown files in the directory. It took some exploration and experimentation to figure out what exactly worked, so I wanted to provide an easy to follow explanation to reduce that friction for future users.

docs: clarify documentation on how to use links

---

lib/default-theme/SearchBox.vue

i'd like to customize suggestions num.
what do you think?
config example:
```
themeConfig: {
searchBox: {
suggestionsMax: 10
}
}
}
```

feat: add suggestions num config

---

docs/guide/markdown.md
lib/util/index.js

Emojis could be written on titles of markdown, but they will not show on the sidebar. So this PR basically contains:
- Fixing for emoji showing as source (e.g. `:tada:`) on sidebar
- Added an emoji to the emoji section to show that this is possible

Fixing emoji not showing on sidebars

---

lib/default-theme/util.js

Current `isActive` checking will fail when a path is prefixed by another. It causes a problem when showing active indicator in the side bar.
eg:
Say we have two pages under `api` folder, which are `uniwebview.md` and `uniwebviewmessage.md`. When accessing `api/uniwebviewmessage.html`, the result when determining side bar active state for `uniwebview` page is:
routePath: "/api/uniwebviewmessage"
pagePath: "/api/uniwebview"
This leads to both uniwebviewmessage and uniwebview be rendered as actived, which is not correct:
By changing it to `===`, it goes fine. However, I am not sure whether there would be a regression on this change or not, since there seems like lack of tests for this project.

Update isActive logic to always checking equality

---

lib/default-theme/SidebarLink.vue

Sidebar links are not clickable unless accurately on the link text. In my opinion, it would be a better UX if the links are clickable even on the whitespace.
This commit includes:
- Changing the width of the `<a>` tags of the sidebar to 100
- Use border-box so that the browser calculates correctly with the padding

Improved mobile UX for sidebar links

---

lib/default-theme/SearchBox.vue

- cursor on search box should be pointer when it is not focused in narrow screen (only the icon is displayed)
- when the screen width is between `$MQNarrow` and `$MQMobile`, the `.suggestions` box may overflow the left edge

tweak: make the SearchBox of default theme better in narrow screen

---

lib/default-theme/DropdownLink.vue

Correction of bug in component without having the key property

Correction of bug in component

---

docs/default-theme-config/README.md
lib/default-theme/Layout.vue

Response to suggestion from #232 - global disabling navbar by themeConfig

Navbar disabling option - global

---

docs/default-theme-config/README.md
lib/default-theme/DropdownTransition.vue

Add built-in search tip in docs and fix a typo

---

lib/app/app.js
lib/default-theme/Layout.vue
package.json

This is still a work in progress, but I'd really like your feedback on the approach so far.
The main idea here is to gather up all of the anchors, then change the hash when the user scrolls beyond one of the anchor headers. I am filtering the anchors so that we only set the hash to links in the sidebar.
Try it in Chrome/Safari, it should work really nicely! Firefox seems to have different behavior when the hash is changed, though. It jumps to the anchors as soon as they're updated. The result is very jerky scrolling, and scrolling up will immediately skip to the top of a section. Any advice for a better way to do this?

Active sidebar link highlight

---

docs/default-theme-config/README.md
lib/default-theme/Page.vue

feat: hide edit link by page (close: #284)

---

lib/util/index.js
lib/util/parseHeaders.js

Fixed: #238 
Test Header:
```md
```

feat: header extraction improvement (close: #238)

---

docs/zh/default-theme-config/README.md

-当你提供了一个 `items` 数组而不是一个单一的 `link` 时，它将会显示以 `下拉列表` 的方式显示：
+当你提供了一个 `items` 数组而不是一个单一的 `link` 时，它显示的将是 `下拉列表` ：

fix: docs "default-theme-config" 出现一处言辞重复

---

lib/prepare.js

fix: index file judgement bug (#306)

---

lib/prepare.js

An alternative to PR #321.
Also related to PR #308 to fix issue #306.
This is to avoid updating node to 8.10 to support *Regex lookbehind*.

Change regex to avoid lookbehind

---

lib/default-theme/styles/mobile.styl
lib/default-theme/styles/theme.styl

fix(navbar): fix styles when navbar is not present

---

docs/config/README.md
docs/guide/markdown.md
lib/markdown/index.js
lib/markdown/link.js

Fixing https://github.com/vuejs/vuepress/issues/186
Alternative approach to https://github.com/vuejs/vuepress/pull/356 and https://github.com/vuejs/vuepress/pull/357.
This approach added `config.markdown.externalLinks` which is an object whose keys and values will be added as a attributes to external links.
cc @ulivz @meteorlxy @mathiasbynens

Global config for links attr

---

lib/default-theme/Page.vue

When `docsDir` is not set, the url to edit the document currently has two slashes.

Avoid duplicate slash when docsDir is not set

---

lib/default-theme/DropdownLink.vue

Fixing https://github.com/vuejs/vuepress/issues/359
The current style forces the dropdown links to have a fixed height which will cause long lines to overlap to the next line. 
This fix removed the fix height and changed the arrow position to `calc(line height - 2px)`
Briefly tested on desktop and mobile. Please review them. 😄 
cc @ulivz @meteorlxy

fixing dropdown overlapping due to word wrapping

---

docs/default-theme-config/README.md

`themeConfig.editLinks` is actually false by default.

Documentation fix

---

lib/default-theme/styles/theme.styl

An updated PR, from discussion in #382.
an overly wide hero image will run out of the container and make the otherwise normally sized page
on mobile horizontally scroll-able
refs: edm00se/awesome-board-games#5
fixes #381

fix(style): sets max-width 100% for images in .content.custom

---

lib/app/util.js

No `page` matches `NotFound.vue`, so we have to provide an empty page object

fix: computed parsing errors in notfound

---

lib/prepare.js

Details in #392
Reference [Modules | Node.js Documentation](https://nodejs.org/api/modules.html#modules_require_resolve_request_options)

fix: resolve custom theme from global cli (#392)

---

lib/dev.js

fix #348 
It's not an issue of `chokidar` but ours, as the glob patterns only work with `/` not `\`.
On Windows, `path` module will resolve `/` to `\`.
https://github.com/paulmillr/chokidar/issues/714
I misunderstood what he meant and made some meaningless conversation... I just want to express my thanks to the guy but he locked it immediately 😅

fix: glob patterns error on windows (#348)

---

lib/app/util.js
lib/code/injectRootMixins.js
lib/prepare.js

I suggest not to introduce `lib/code/`, which is not necessary

refactor: the root mixins injection

---

docs/guide/using-vue.md
docs/zh/guide/using-vue.md

---
Docs broke after https://github.com/vuejs/vuepress/commit/d0ef06f5944aada7b5e03fd50eb7f4963fe75d5b
---
---

fix: docs broke after previous fix

---

lib/default-theme/Home.vue

I noticed in the browser devtools that the default theme tried to use `align-content: strech`. This must've been a typo 🙂

Fix typo in home styling

---

lib/default-theme/styles/code.styl
lib/markdown/highlight.js

````
```ts
const test = "test code"
```
````
---
---

chore: language-ts alias and highlight support

---

lib/app/Content.js

> Details explained by Evan: https://github.com/vuejs/vue-loader/issues/1014#issuecomment-338281037
close #429
When using `<Content>` like this:
```
<Content class="post-content markdown-body"/>
```
---
---

chore: allow class and style merging for content

---

lib/default-theme/styles/code.styl
lib/markdown/highlightLines.js
lib/markdown/preWrapper.js

This issue was introduced by fixing #350 at d0ef06f5944aada7b5e03fd50eb7f4963fe75d5b, and due to `<span> in <code> cannot expand to 100% width of <code>`.
Since we have hoisted `pre-wrapper` as a standalone plugin at 45a3df5162834abf2c205ccaa4135f23e44e3ece, we can also hoist the highlight lines element as an adjacent element to `<pre>` and create new stacking context to implement the same function.
BTW, the advantage of this PR is that we can avoid modifying the code in `<pre><code>` directly.

fix: highlight lines are cut when sliding

---

lib/dev.js
package.json
yarn.lock

close #424
related https://github.com/webpack-contrib/webpack-serve/issues/135
---
---

fix: upgrade webpack-serve and avoid port conflict

---

lib/app/app.js
lib/default-theme/NavLink.vue
lib/default-theme/NavLinks.vue
lib/default-theme/Page.vue
lib/markdown/link.js

This PR includes the following enhancements
- Replaced `addAttr()` by `token.attrSet()`
- Show OutboundLink icon for external links in nav
- Show OutboundLink icon for external links in markdown

Show OutboundLink icon for external links

---

docs/default-theme-config/README.md
lib/default-theme/Layout.vue

Auto setting the active hash based on the side bar links and page headers was having some non-ideal behaviors on my site. If you have headers that aren't in the side bar, or update the hash programmatically this feature can cause issues.
I introduced a …

feat: allow for disabling of active hash on scroll (#482)

---

lib/markdown/link.js
test/markdown/__snapshots__/link.spec.js.snap
test/markdown/link.spec.js

cc @yyx990803.
- https://vue-test-utils.vuejs.org/api/#mount (Click: `See also:Wrapper`, it will go to homepage.)
- http://www.v2js.com/vuepress-link/ (This link gives all possible situations)
Assuming you have following directory structure:
``` md.
docs
├── README.md
└── guide
├── README.md
├── item-1.md
└── item-2.md
```
When you use `[~](guide/README.md)` at `docs/README.md`, the expected output href should be `/guide/` instead of `/`.
Also, when you use `[~](README.md)`  at `docs/guide/item-1.md`, the expected output href should be `/guide/` instead of `/`.
With this PR, you can even use `../`.
This PR also supports the usage of relative paths for all cases and doesn't force a absolute paths beginning with `/`. so vuepress's intrusion on md files has also been reduced to a minimum. …

feat: support generic markdown file path reference

---

lib/app/dataMixin.js

**Summary**
It seems more common (and better IMO) to put current page title before the site title. Some examples:
- Vue official docs
- [Console API Reference  |  Tools …

show current page title in front of site title

---

lib/default-theme/SidebarGroup.vue

Add padding to both sides of .sidebar-heading instead of left only
**Summary**
**Before:**
**After:**

fix: increase sidebar-heading padding

---

docs/config/README.md
docs/zh/config/README.md
lib/build.js

feat: control BundleRenderer shouldPrefetch option (#463)

---

docs/guide/markdown.md
lib/markdown/index.js
lib/markdown/snippet.js
test/markdown/__snapshots__/snippet.spec.js.snap
test/markdown/fragments/code-snippet-highlightLines-multiple.md
test/markdown/fragments/code-snippet-highlightLines-single.md
test/markdown/fragments/code-snippet.md
test/markdown/fragments/snippet.js
test/markdown/snippet.spec.js

Add rule to import code snippets:
``` md
...
rollup-plugin-vue ships as zero config solution to package `.vue` files.
<<< @/cookbook/minimal/rollup.config.js{1,10}
```

feat: Add support to import files as code fence

---

docs/guide/markdown.md
lib/app/app.js
lib/default-theme/Badge.vue
lib/default-theme/styles/custom-blocks.styl
lib/default-theme/styles/theme.styl
lib/default-theme/styles/toc.styl
lib/markdown/index.js
lib/util/index.js
lib/util/parseHeaders.js
lib/util/shared.js

Headers badge

---

docs/guide/using-vue.md
docs/zh/guide/using-vue.md

**Summary**
fixed: the hook name 'beforeMounted' should be 'beforeMount' according to https://vuejs.org/v2/api/#beforeMount

fix: typo: hook name 'beforeMounted' should be 'beforeMount' in docs.

---

lib/dev.js
package.json
yarn.lock

add 'koa-range'(https://github.com/koajs/koa-range) to dev.js.
it enable range request in development.
without "Content-Range", safari cannot play and show video.
**Summary**
**Other …

feat: enable header request Content-Range

---

lib/default-theme/Page.vue
yarn.lock

The edit page from Bitbucket (is used a GET request with some parameters) is different from Gitbhub ( add /edit ). For example:
Bitbucket: https://bitbucket.org/myrepo/bitbucket-vuepress/src/master/docs/README.md?mode=edit&spa=0&at=master (This not exist)
Github: https://github.com/vuejs/vuepress/edit/master/docs/README.md
For test I create a repository in Bitbucket with vuePress and worked!
**Summary**
You have tested in the following browsers: (Providing a …

fix: edit page from Bitbucket

---

lib/util/parseHeaders.js

**Summary**
Fixes issue for bold and italic text in headers  as well as multiple sets of tokens 
```markdown
```
Currently, only the one set of tokens is removed from the table of contents and sidebar links:
Change makes the regexp non-greedy for matching the token pairs (`*?`) and matches up to 3 pairs of asterisks (`\*{1,3}`). 
N/A
If adding a **new feature**, the PR's …

fix: multiple markdown tokens regexp

---

lib/default-theme/DropdownLink.vue
lib/default-theme/NavLinks.vue

**Summary**
The `.nav-item` div around each navbar link currently has an explicit `cursor: pointer` style. However it's slightly higher than its contained link. This makes the styling undesirable since it tricks the user into thinking that they could click there to follow the link.
1. This pull request removes that style. It remains present on the link itself through the user agent stylesheet.
2. Interactive nav items without any links (currently only dropdowns) should still be receiving their cursor style independently. This is also done by this pull request for the `.dropdown-wrapper` class.
Note how the cursor does not actually touch …

Remove cursor style from nav link container

---

lib/webpack/createBaseConfig.js

Prevents picking up local `.babelrc` file in projects.
Babel options can be configured with `chainWebpack` in config by doing
`config.module.rule('js').use('babel-loader').tap(options => ({
...options, plugins: [] }))`
I found this while adding live examples to vue-router docs
**Summary**
To avoid wasting your …

fix: set babelrc: false in babel-loader options

---

lib/prepare/resolveOptions.js

**Summary**
Fixes #654
Dest folder, if present in the config, gets excluded from pageFiles to prevent parsing errors if any .md file's present.

fix: exclude dest folder from pageFiles (fixes #654)

---

lib/default-theme/styles/code.styl

**Summary**
`py` could not display in the top right corner of code block
**Before**
**After**

fix: could not display py lang in code block

---

docs/default-theme-config/README.md

**Summary**
We want to introduce [the new way DocSearch will handle search on different languages for vuepress](https://github.com/algolia/docsearch-configs/commit/85a5791e2f98755fce93ca35595c698e2c28a54f).
It will not more be needed to use the URL as it might introduce issue. We will grab it ourselves from the DOM (attribute `lang`).
You can now update the vuepress website (couldn't find the website's repo):
```html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.css" />
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js"></script>
<script type="text/javascript"> docsearch({
apiKey: '3a539aab83105f01761a137c61004d85',
indexName: 'vuepress',
inputSelector: '### REPLACE ME ####', …
```

enhancing DocSearch integration with language

---

lib/util/parseHeaders.js
test/util/parseHeaders.spec.js

**Summary**
Since VuePress needs to extract the header from the markdown source file and display it in the sidebar or title (#238), this file(`lib/util/parseHeaders.js`) simply removes some unnecessary elements to make header displays well at sidebar or title.
But header's parsing in the markdown content is done by the markdown loader based on markdown-it. markdown-it parser will will always keep HTML in headers, so in VuePress, after being parsed by the markdiwn loader, the raw HTML in headers will finally be parsed by Vue-loader. so that we can write HTML/Vue in the header. One exception is the HTML wrapped by `<code>`(markdown token: '`') tag.
This PR is to support writing HTML(Vue) anywhere in the header, not just at the end of the header.
Some key points about this PR:
1. Write …

feat: support writing HTML(Vue) anywhere in the header.

---

lib/prepare/loadConfig.js

fix: skip format data.head if not exist while loading toml config

---

docs/default-theme-config/README.md
lib/prepare/index.js

Hello @ulivz, it's been a while! I just came back from holiday and looks like there are a lot of things happened in VuePress! All very exciting and looking cool! Thank you so much for the hard work! ❤️
Just a quick suggestion after upgrading to the latest VuePress. 
**Summary**
Referring to `config.styl` variables inside `style.styl` is probably a common thing. E.g. Useful for media query, text colors etc...
I think it makes sense if we expose the variables in `style.styl` by default.

feat: expose config.styl variables to style.styl

---

docs/default-theme-config/README.md

**Summary**
This PR fixes some grammatical mistakes.

Theme config grammar fixes

---

packages/@vuepress/core/lib/internal-plugins/routes.js
packages/@vuepress/core/lib/prepare/AppContext.js
packages/@vuepress/core/lib/prepare/Page.js
packages/@vuepress/core/lib/prepare/util.js
packages/@vuepress/theme-default/src/Layout.vue
packages/@vuepress/theme-default/src/Sidebar.vue
packages/@vuepress/theme-default/src/util.js
packages/docs/docs/guide/assets.md

Permalinks refer to the URLs (excluding the domain name) for your pages and posts. 
**Demo**: 
[vuepress-permalink.zip](https://github.com/vuejs/vuepress/files/2315946/vuepress-permalink.zip)
1. Global (For blog)
```js
permalink: ':year/:month/:day/:slug'
}
```
2. Specific page
``` md
---
permalink: :year/:month/:day/:slug
date: 2018-08-14 11:22:33
---
```
- **sourceDir**: docs
- **filename**: docs/_posts/evan you.md
- **content**: 
``` md
---
permalink: :year/:month/:day/:slug
date: 2018-08-14 11:22:33
---
```
- **asserts**: 
| pattern | permalink |
| --- | --- |
| :year/:month/:day/:slug/ | 2018/08/14/evan-you/ |
| :year-:month-:day-:slug/ | 2018-08-14-evan-you/ |
| :year/:month/:day/:title/ | 2018/08/14/yyx 990803/ |
| :year/:month/:day/:original/ | …

Blog stage 1 - permalink

---

docs/default-theme-config/README.md
lib/util/logger.js

**Summary**
Remove `module.exports.getLoggerFn = getLoggerFn`.
After `logger[type] = getLoggerFn(color, label)`, this function doesn't execute anymore so I think there is no need to export getLoggerFn.
To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before …

chore: do not need to export getLoggerFn

---

packages/@vuepress/core/lib/prepare/loadTheme.js

**Summary**
fs.exists() is [deprecated](https://nodejs.org/api/fs.html#fs_fs_exists_path_callback), and using it without a callback causes the error **TypeError …

fix($core): useLocalTheme should be set to true when localThemePath exists and contains file

---

lib/dev.js

Closes #855
When running vuepress dev, chokidar is set to observe all
addition/removal of md files inside the current folder.
`node_modules` is one of the observed folders and can contain tons of subfolders. It mostly never contains any md files. Even more rarely has it any hot additions of md files.
Another perk of this fix is this: If for some reason a developer
decided to publish a folder with a weird name in its module. It will not
prevent `vuepress dev` from loading.
**Summary**
**The PR …

fix #855 Stop observing add/remove of files in node_modules

---

packages/@vuepress/core/lib/prepare/loadTheme.js

**Summary**
In the absence of a theme entry file, an extra anonymous plugin load
message would be printed as the themeEntryFile object lacked a name.
This change corrects that.
**Other …

fix($core): fix extra anonymous plugin message

---

packages/@vuepress/plugin-pagination/index.js

**Summary**
This fixes a minor bug where the pagination plugin calculates the wrong number of pages when the pages fit exactly. For example, if you have 20 posts, it shows 3 pages instead of 2.
To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on …

Fix pages number in the pagination plugin

---

packages/docs/docs/guide/basic-config.md

**Summary**
The page 'Custom Theme' looks have gone. The link should lead visitors to the page ['Writing a theme'](https://vuepress.vuejs.org/theme/writing-a-theme.html).
**Other …

The link to Custom Theme leads to 404

---

packages/@vuepress/plugin-blog/index.js
packages/docs/docs/plugin/official/plugin-blog.md

**Summary**
The VuePress blog plugin provides an opinionated default for the URL of blog posts. As of v1.0.0-alpha.20 changing the permalink URL of blog posts is only possible via passing a custom "pageEnhancer" to `plugin-blog`. That pageEnhancer basically overwrites `page.frontmatter.permalink`. This workaround `config.js` looks similar to:
```javascript
plugins: {
'@vuepress/blog': {
pageEnhancers: [{
when: page => page.type === 'post',
frontmatter: {permalink: '/custom/permalink/:slug'}
}]
}
}
```
To simplify the solution, this PR adds a new configuration option `permalink` to the blog plugin that allows to configure the permalink URL for blog posts. The new configuration option uses the same default as previously:
```javascript
plugins: { …
```

feat($plugin-blog): Allow the permalink for blog posts to be configured.

---

packages/@vuepress/plugin-blog/index.js
packages/docs/docs/plugin/official/plugin-blog.md
packages/docs/docs/zh/plugin/official/plugin-blog.md

**Summary**
Current blog plugin use `_posts` as the posts directory and could not be changed (no docs about that, too). Make this option configurable would be better.

feat($plugin-blog): add postsDir option

---

packages/@vuepress/plugin-medium-zoom/mixin.js
packages/@vuepress/plugin-medium-zoom/package.json

**Summary**
medium-zoom doesn't get attached to newly loaded images when the user navigates to other routes within a vuepress project. The problem is that medium-zoom gets attached to currently available images when the LayoutDistributor is mounted, but not when it's updated (e.g. when the user navigates to a new route).
My fix detaches all images from medium-zoom when the LayoutDistributor updates (as images could have been removed from the DOM) and attaches all current images in the DOM which match the provided selector.
If yes, please describe the impact and migration path for …

🐛 Fix medium-zoom not updating on component update

---

packages/@vuepress/plugin-active-header-links/index.js
packages/@vuepress/plugin-active-header-links/mixin.js
packages/docs/docs/plugin/official/plugin-active-header-links.md

**Summary**
Allowing the addition of a theme that is not the default VuePress theme, the header is not always going to be 90.  This PR allows you to define the option of the top offset from the configuration of the plugin. …

Adds option for specifying the top offset

---

packages/@vuepress/theme-default/components/Home.vue

**Summary**
Before:
After:
Wide `.hero > img` image doesn't fit into `.hero` horizontally.
Widescreen view isn't changed:

Fit image into parent block horizontally

---

packages/@vuepress/core/lib/app/root-mixins/updateLoadingState.js

**Summary**
closes #1011 
The URL doesn't update because of `e.preventDefault()` called in an event listener attached to all anchor links. My fix updates the displayed URL to reflect the change but doesn't break the smooth scroll to the anchor tag (which is why `e.preventDefault()` is being called in the first place).
Note: The smooth scrolling doesn't work in Safari, it just jumps to the anchor tag immediately. My PR doesn't change that behaviour.
You have …

🐛 Fix #1011 anchor links not updating current URL

---

packages/@vuepress/core/lib/build.js

**Summary**
This PR simply changes `fs.remove` during build/`build.js` to `fs.emptyDir`. This arose due to a semi-funky build system in which we are building the documentation via Docker container into a Docker volume which is also attached to an NGINX container which has the `.vuepress/dist` folder mounted as a Volume and served via NGINX. `fs.remove` attempts to unlink the `dist` folder, causing a build failure due to the NGINX mount. `emptyDir` simply empties …

Empty build output directory instead of remove

---

packages/docs/docs/theme/default-theme-config.md

The docs show how to have sub groups inside a dropdown menu by having nested items. However, the example link text for Chinese and Japanese does not work as expected.  Add the necessary trailing forward-slashes so that the code works as expected if somebody was to cut-and-paste the example as is.
**Summary**
- [X ] Docs
- [ X] No
- [X ] Chrome
- [X ] Firefox
- [ X] Edge
If …

Added trailing forward-slashes in link properties

---

packages/@vuepress/cli/index.js
packages/@vuepress/cli/package.json
yarn.lock

Migrate to CAC

---

packages/@vuepress/core/lib/app/components/Content.js
packages/docs/docs/guide/markdown-slot.md

**Summary**
Fix content component to use `slotKey` instead of unavailable `slot` prop. Clean up readme with consistent example.
Fixes #1048

fix #1048: use slotKey prop for markdown slots

---

packages/@vuepress/core/lib/prepare/AppContext.js

**Summary**
Noticed the `--dest` CLI option wasn't working. It looks like https://github.com/vuejs/vuepress/commit/df99cb6e4bcb692707cefedbc190c0121f140c5b broke it. …

feat($core): AppContext was still expecting --outDir instead of --dest

---

packages/@vuepress/theme-default/components/Navbar.vue

**Summary**
Currently the the template renders the following invalid CSS with maxwidth "null" in the server side pre-rendered HTML page
````<div class="links" …
```

handle SSR when linksWrapMaxWidth is null

---

packages/@vuepress/core/lib/internal-plugins/frontmatterBlock/index.js
packages/@vuepress/core/lib/internal-plugins/frontmatterBlock/loader.js
packages/@vuepress/core/lib/internal-plugins/routes.js
packages/@vuepress/core/lib/prepare/AppContext.js
packages/@vuepress/core/lib/prepare/Page.js
packages/@vuepress/shared-utils/__tests__/isIndexFile.spec.js
packages/@vuepress/shared-utils/index.js
packages/@vuepress/shared-utils/lib/fileToPath.js
packages/@vuepress/shared-utils/lib/isIndexFile.js
packages/@vuepress/shared-utils/lib/parseVueFrontmatter.js

feat($core): Vue SFC as source files

---

packages/@vuepress/cli/package.json
yarn.lock

**Summary**
Bumping cac to at least v6.3.6 to include the fix for https://github.com/cacjs/cac/issues/34
Since the introduction of cac to vuepress, the command line …

fix($cli): bump CAC version

---

packages/@vuepress/core/lib/plugin-api/override/AdditionalPagesOption.js
packages/@vuepress/core/lib/plugin-api/override/instantiateOption.js
packages/@vuepress/core/lib/prepare/AppContext.js
packages/docs/docs/plugin/option-api.md

**Summary**
Add support of async function for `additionalPages` plugin option as already described in the [docs](https://vuepress.vuejs.org/plugin/option-api.html#additionalpages).
Fixes #1077

fix #1077: async function support for additionalPages plugin

---

packages/@vuepress/core/lib/app/app.js
packages/@vuepress/core/lib/app/root-mixins/updateLoadingState.js
packages/@vuepress/core/package.json
yarn.lock

**Summary**
closes #1071 
→ see #1071 
I removed `smooth-scroll` as it was causing issues when used with `active-header-links`.

✨ Router scroll behaviour, fix #1071

---

packages/docs/docs/config/README.md
packages/docs/docs/zh/config/README.md

slugify source code link broken.
**Summary**

Update slugify source link

---

packages/@vuepress/core/lib/internal-plugins/palette/index.js
packages/@vuepress/core/lib/internal-plugins/style/index.js

**Summary**
- not browser related
This is a window related bug, which was fixed in a previous version but not in `1.x.x`.
See [this pull request](https://github.com/vuejs/vuepress/pull/692) for further information

fix: normalize override stylus file path in windows

---

packages/@vuepress/core/lib/internal-plugins/frontmatterBlock/loader.js
packages/@vuepress/core/package.json
packages/@vuepress/markdown-loader/index.js
packages/@vuepress/markdown/__tests__/util.js
packages/@vuepress/shared-utils/src/extractHeaders.ts

**Summary**
Why does an LRU Class not use the new operator? Caused an error Uncaught TypeError: Class constructor LRU cannot be invoked without 'new'
i use `npm install`, the lru-cache is 5.x.  but vuepress dep is 4.x
**I found out why lru-cache became 5.x.
The reason is because @vue/cli-shared-utils uses ^5.1.1**
Source location: https://github.com/isaacs/node-lru-cache/blob/master/index.js#L27
You have tested in the following browsers: (Providing a detailed …

fix: LRU does not use the "new" operator

---

packages/@vuepress/theme-default/components/AlgoliaSearchBox.vue
packages/@vuepress/theme-default/components/Home.vue
packages/@vuepress/theme-default/components/Page.vue
packages/@vuepress/theme-default/components/Sidebar.vue
packages/@vuepress/theme-default/components/SidebarGroup.vue

**Summary**
See #1154 for info – this replaces some `div`s with `header`/`main`/`aside` tags and adds an aria landmark to the search
Merging this PR closes #1154

feat #1154: use semantically more meaningful tags

---

packages/docs/docs/guide/deploy.md

[Doc] Update deploy.md for Now 2.0

---

packages/@vuepress/markdown/lib/component.js

**Summary**
This removes an unnecessary `console.log` from the `markdown/lib/component.js` that was causing HTML_SEQUENCES to be displayed during `dev` and `build`
fix #1155 
**Other …

Removes unnecessary console.log

---

packages/@vuepress/plugin-pagination/index.js

**Summary**
fix again pagination calculates the wrong intervallers, eg. when I have 2 posts, I pass  perPagePosts is 1. but the pagination will calculates theintervallers is ```[ [ 0, 0 ], [ 1, 1 ] ]``` instead of ```[ [ 0, 1 ], [ 1, 2 ] ]```
```javascript
const path = require('path')
name: 'vuepress-theme-ihaoze',
plugins: [
'@vuepress/blog',
['@vuepress/pagination', {
perPagePosts: 1
}],
[
'@vuepress/register-components', {
componentsDir: [
path.resolve(__dirname, 'components')
]
}]
]
}
```
If yes, please describe the impact and migration path for existing …

fix pagination

---

packages/@vuepress/core/__tests__/plugin-api/PluginUtil.spec.js
packages/@vuepress/core/lib/dev.js
packages/@vuepress/core/lib/webpack/createBaseConfig.js

**Summary**
when you set base config, you will get a `404` error

fix: #1238, fix 404 when base config is not '/'

---

packages/@vuepress/core/lib/prepare/loadTheme.js

**Summary**
- fix typo `layourDir` to `layoutDir`
- fix bug that never throw error when `Layout.vue` does not exist
- fix typo that the `filename` of default `NotFound.vue` is `Layout.vue`

fix($core): load theme bug and typo

---

packages/@vuepress/core/package.json
packages/@vuepress/markdown-loader/package.json
packages/@vuepress/markdown/package.json
packages/@vuepress/plugin-active-header-links/package.json
packages/@vuepress/plugin-back-to-top/package.json
packages/@vuepress/plugin-blog/package.json
packages/@vuepress/plugin-google-analytics/package.json
packages/@vuepress/plugin-i18n-ui/package.json
packages/@vuepress/plugin-last-updated/package.json
packages/@vuepress/plugin-medium-zoom/package.json
packages/@vuepress/plugin-notification/package.json
packages/@vuepress/plugin-nprogress/package.json
packages/@vuepress/plugin-pagination/package.json
packages/@vuepress/plugin-pwa/package.json
packages/@vuepress/plugin-register-components/package.json
packages/@vuepress/plugin-search/package.json
packages/@vuepress/shared-utils/package.json
packages/@vuepress/test-utils/package.json
packages/@vuepress/theme-blog/package.json
packages/@vuepress/theme-default/package.json
packages/@vuepress/theme-vue/package.json
packages/vuepress/package.json

**Summary**
I created a similar PRs in vue-cli and vue repos, so I will just copy&paste my comment here:
This field allows you specify path of each package in a monorepo thanks to [this npm RFC](https://github.com/npm/rfcs/blob/latest/accepted/0010-monorepo-subdirectory-declaration.md). Main benefit of providing this field is a more accurate link to the package's source code from its npmjs.com page.
You have tested in the following browsers: (Providing a …

chore: add `repository.directory` field to each `package.json`

---

packages/docs/docs/guide/deploy.md

Hosting with AWS Amplify

---

.eslintrc.js
packages/@vuepress/theme-default/components/Page.vue
packages/@vuepress/theme-default/components/Sidebar.vue
packages/@vuepress/theme-default/components/SidebarGroup.vue
packages/@vuepress/theme-default/components/SidebarLink.vue
packages/@vuepress/theme-default/components/SidebarLinks.vue
packages/@vuepress/theme-default/styles/theme.styl
packages/@vuepress/theme-default/util/index.js
packages/docs/docs/.vuepress/config.js
packages/docs/docs/theme/default-theme-config.md
packages/docs/docs/zh/theme/default-theme-config.md

**Summary**
This PR contains following features:
1. `sidebarDepth` for a specified sidebar group;
```js
themeConfig: {
sidebarDepth: 1, /* Default sidebar depth */
sidebar: [
{
title: 'foo',
sidebarDepth: 2,  /* Override default sidebar depth for current sidebar */
children: [
['', 'README'],
'a',
'b',
'c',
'd'
]
}
]
}
}
```
e.g. 
- Change:
- Before | After
2. Nested sidebar groups;
```js
themeConfig: {
sidebar: [
{
title: 'foo',
children: [
['', 'README'],
'a',
'b',
{
title: 'foo/child',
children: [
'c',
'd'
]
}
]
}
]
}
}
```
3. Clickable heading for sidebar groups.
```js
themeConfig: {
sidebar: [
{
title: 'foo',
path: '/foo/', /* Sidebar of current heading will be clickable like a route link */
children: [
['', 'README'],
'a', …
```

feat($theme-default): refine sidebar groups

---

packages/@vuepress/core/lib/app/app.js
packages/@vuepress/core/lib/app/redirect.js

In VuePress, we have following convention about routing:
- `/foo/` means source file is `/foo/{README|index}.md`
- `/foo.html` means your source file is `/foo.md`
The original design of VuePress relied on above two styles
of routing, especially the calculation involved of routes at
// default theme. so we can't easily modify `/foo.html` directly
to `/foo` (i.e. remove html suffix)
This  utility handles redirect of clean urls, with this utility, you'll
get:
For unknown request `/foo`
- redirect to `/foo.html` if it exists
- redirect to `/foo/` if it exists
For unknown request `/foo/`
- redirect to `/foo.html` if it exists
If all the above redirect rules don't exist, you'll get a 404
---
**Note that** this PR doesn't provide you the ability to remove the
html suffix at the route level, it …

feat($core): redirects for clean urls

---

packages/@vuepress/theme-default/components/Navbar.vue

This allows Navbar.vue in the default theme to not display the search bar on a page-by-page basis, by reading the search attribute of frontmatter.
**Summary**
Allow disabling of Search in Navbar via frontmatter search property.

Disable Search For Each Page (fix #1287)

---

packages/docs/docs/.vuepress/components/Bit.vue

**Summary**
The docs site currently points to a Bit (bitsrc.io) sponsor logo asset at https://raw.githubusercontent.com/vuejs/vuejs.org/master/themes/vue/source/images/bit-wide.png which [does not](https://github.com/vuejs/vuejs.org/blob/master/themes/vue/_config.yml) [exist](https://github.com/vuejs/vuejs.org/tree/master/themes/vue/source/images) in the vuejs/vuejs.org repo causing a 404 (see screenshot below).  This PR points it to the similarly name asset that _does_ exist.
**The PR fulfills these …

Fix Bit sponsor image

---

packages/@vuepress/plugin-pwa/lib/enhanceAppFile.js

**Summary**
Close: #1271
cc @mysticatea 

fix($plugin-pwa): set current registration scope for service worker (Close: #1271)

---

packages/docs/docs/theme/default-theme-config.md

Add small section for disabling search per page via new front matter property search.
**Summary**

Default Theme Docs: Disable Search per Page

---

packages/@vuepress/markdown-loader/index.js
packages/@vuepress/markdown/lib/link.js

**Summary**
**feat: support env.loader**
User can get access to markdown-loader using `env.loader`. Example:
```js
module.exports = (md, options) => { …
```

feat($markdown): refine markdown api

---

packages/@vuepress/theme-default/components/Home.vue

this is useful when `data.heroImage` can act as the "header" _(e.g. logo & label of product / application are present in image)_
- allow removing the h1 tag when `data.heroText` is `NULL`
- allow passing `data.heroAlt` to define alt text value.
**Summary**
> with `data.heroText === null`
- [ x IE
- I have not …

Proposal: Hero Header should allow for optional h1 text

---

packages/@vuepress/core/lib/app/components/OutboundLink.vue

**Summary**
This will update outbound link icon alignment.
| Before (header) | After (header) |
| ------ | ------ |
| ![image](https://user-images.githubusercontent.com/120486/53301379-ddbeec80-385a-11e9-9235-cf1ebcdc3ba1.png) | ![image](https://user-images.githubusercontent.com/120486/53301380-e1eb0a00-385a-11e9-8bd1-a02341bf38e2.png) |
| Before (paragraph) | After (paragraph) |
| ------ | ------ |
| ![image](https://user-images.githubusercontent.com/120486/53301383-e7485480-385a-11e9-9b91-24ed501c4bab.png) | ![image](https://user-images.githubusercontent.com/120486/53301386-ec0d0880-385a-11e9-9f3d-c2e4e72ce9c2.png) |
**Does this PR …

Update outbound link icon alignment

---

packages/docs/docs/zh/guide/deploy.md

fix: docs link

---

packages/@vuepress/plugin-clean-urls/.npmignore
packages/@vuepress/plugin-clean-urls/README.md
packages/@vuepress/plugin-clean-urls/index.js
packages/@vuepress/plugin-clean-urls/package.json
packages/docs/docs/.vuepress/config.js
packages/docs/docs/plugin/official/plugin-clean-urls.md
packages/docs/docs/zh/plugin/official/plugin-clean-urls.md

**Summary**
Add a new plugin `@vuepress/vuepress-plugin-clean-urls`.
This plugin supports two options:
- Type: `string`
- Default: `''`
The suffix for normal pages. For …

feat: plugin clean urls

---

packages/@vuepress/markdown-loader/index.js
packages/@vuepress/markdown-loader/package.json
packages/@vuepress/markdown/index.js
packages/@vuepress/markdown/package.json

**Summary**
Cache `markdown.parse` instead of `markdown.render`.

feat($markdown): markdown cache parser

---

packages/@vuepress/theme-default/util/index.js

Co-Authored-By: MeetInInc <meetininc@users.noreply.github.com>
**Summary**

fix($theme-default): encodeURI for sidebar items which contain CJK characters (close: #717)

---

packages/@vuepress/core/lib/build.js
yarn.lock

**Summary**
This pr addresses the issue #1367. When source-map is enabled, the previous implementation won't generate runnable output.
This build-related fix manages to generate runnable output when source-map is enabled at the price of an additional unnecessary chunk. However, source-map in production mode is mainly used to debug production bundle, thus does not affect normal users.
You have tested in the following browsers: (Providing a detailed version will …

fix #1367: Generate runnable output when source-map is enabled

---

packages/@vuepress/core/lib/prepare/loadTheme.js

fix($core): support theme index file which is not at root (close: #1362)

---

packages/@vuepress/core/lib/app/app.js
packages/@vuepress/core/lib/app/components/HeaderList.vue
packages/@vuepress/core/lib/app/components/TOC.vue
packages/@vuepress/markdown/index.js
packages/@vuepress/markdown/lib/tableOfContents.js
packages/@vuepress/markdown/package.json
packages/docs/docs/config/README.md
packages/docs/docs/guide/markdown.md
packages/docs/docs/guide/using-vue.md
packages/docs/docs/zh/config/README.md
packages/docs/docs/zh/guide/markdown.md
packages/docs/docs/zh/guide/using-vue.md

**Summary**
TOC component provides an ability to access the current page structure. For example, with TOC component, we can easily support a table of contents that …

feat($markdown): TOC component (close: #1275)

---

packages/@vuepress/markdown/__tests__/__snapshots__/snippet.spec.js.snap
packages/@vuepress/markdown/__tests__/snippet.spec.js
scripts/test.js

test: fix snippet test

---

packages/@vuepress/plugin-blog/index.js

**Summary**
It seems `layoutComponentMap` has been refactored into `themeAPI`, correct the reference in `plugin-blog`.

fix(plugin-blog): read layoutComponents from themeAPI

---

packages/@vuepress/core/lib/client/app.js
packages/@vuepress/core/lib/client/components/Content.js
packages/@vuepress/core/lib/client/plugins/VuePress.d.ts
packages/@vuepress/core/lib/client/plugins/VuePress.js
packages/@vuepress/core/lib/client/util.js
packages/@vuepress/core/lib/node/internal-plugins/layoutComponents.js
packages/@vuepress/core/lib/node/internal-plugins/pageComponents.js
packages/@vuepress/core/lib/node/internal-plugins/routes.js

refactor($core): auto register layouts and pages (for #1402)

---

packages/@vuepress/core/lib/node/Page.js
packages/@vuepress/theme-default/components/Page.vue

fix($theme-default): fix wrong editLink (close: #1115, #1125)

---

packages/@vuepress/core/lib/node/plugin-api/index.js
packages/@vuepress/core/lib/node/plugin-api/util.js
packages/@vuepress/markdown/index.js
packages/@vuepress/shared-utils/src/index.ts
packages/@vuepress/shared-utils/src/moduleResolver.ts
packages/@vuepress/shared-utils/src/normalizeConfig.ts
packages/docs/docs/config/README.md
packages/docs/docs/zh/config/README.md

feat($markdown): markdown plugin (close: #585)

---

packages/@vuepress/theme-default/global-components/Badge.vue

**Summary**
Expanded the functionality of prop `vertical`.

feat($theme-default): refine badge

---

packages/docs/docs/guide/markdown.md
packages/docs/docs/zh/guide/markdown.md

**Summary**
- add refs to custom container
- update some badges
- add some chinese translation

docs: add refs to custom container

---

packages/@vuepress/core/lib/client/components/Content.js

Registering component in render function is throwing unknown component. In fact, there is no need to register component as `h` can accept async factory (async component)
**Summary**
**Other …

fix: Do not register component in render function

---

packages/docs/docs/miscellaneous/design-concepts.md

Fix broken link

---

rfcs/002.plugin-git-log.md

[Rendered](https://github.com/vuejs/vuepress/blob/rfc/plugin-git-log/rfcs/002.plugin-git-log.md)

[RFC] plugin-git-log

---

packages/docs/docs/config/README.md
packages/docs/docs/guide/deploy.md
packages/docs/docs/zh/config/README.md
packages/docs/docs/zh/guide/deploy.md

**Summary**
No changes provided to the UI of the default theme.
No breaking change has been introduced.
No specific issue has been created/referenced.
Not necessary. Introducing changes into the documentation only.
To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval …

docs: fix github brand name usage

---

packages/@vuepress/plugin-active-header-links/clientRootMixin.js

**Summary**
Fixes issue #865 wherein if the bottom element is too small, navigating to the hash will cause the url to change to the element displayed at the top of the page. For example:
**The Problem:**
Note how clicking on "Advanced Configuration" causes the "Insert Code Snippets" navigation item to be selected and hash to be reflected in the URL
**Fixed:**
Note how clicking on "Advanced Configuration" remains selected
You have tested in the following …

fix nav url change bug (#865)

---

packages/@vuepress/core/lib/client/components/OutboundLink.vue

**Summary**
`stylus-loader` is not a dependency of `@vuepress/core`, so stylus should not be used in `OutboundLink.vue`.

fix($core): do not use stylus in outbound link

---

packages/@vuepress/plugin-active-header-links/clientRootMixin.js

**Summary**
In some cases, the code from #1475 can render the page unable to scroll in response to a click in the side navigation.
**Issue:**
**Fixed:**
This is …

Fix side navigation edge case bug introduced in #1475

---

packages/@vuepress/core/lib/node/Page.js
packages/@vuepress/markdown-loader/index.js
packages/@vuepress/markdown/index.js
packages/@vuepress/markdown/lib/link.js

**Summary**
Use `relativePath` instead of `relPath`.

$markdown: use `relativePath` instead of `relPath`

---

packages/@vuepress/core/lib/node/webpack/createBaseConfig.js
packages/docs/docs/config/README.md
packages/docs/docs/zh/config/README.md

**Summary**
`siteConfig.evergreen` has no access to many properties of `context`:
```js
// config.js
module.exports = ({ isProd }) => ({
evergreen: !isProd
// always `true`, because `context.isProd` is
// `undefined` when `config.js` is applied
})
```
Now we can use the following config:
```js
// config.js
module.exports = (context) => ({
evergreen: () => !context.isProd
// dev: `true`
// build: `false`
})
```
You have tested in the following browsers: …

feat($core): functional siteConfig.evergreen

---

lib/markdown/snippet.js
test/markdown/__snapshots__/snippet.spec.js.snap
test/markdown/fragments/code-snippet-with-space-in-path.md
test/markdown/fragments/snippet with spaces.js
test/markdown/snippet.spec.js

**Summary**
**Other information:** I hope the test is wanted. I'm (selfishly) submitting this to the 0.x branch, since that's the version I use, but I think this would need to be applied to …

Fix #1505 - Snippets should not split path on space

---

packages/@vuepress/markdown/__tests__/__snapshots__/snippet.spec.js.snap
packages/@vuepress/markdown/__tests__/fragments/code-snippet-with-space-in-path.md
packages/@vuepress/markdown/__tests__/fragments/snippet with spaces.js
packages/@vuepress/markdown/__tests__/snippet.spec.js
packages/@vuepress/markdown/lib/snippet.js

**Summary**
Ports 0.x fix from https://github.com/vuejs/vuepress/pull/1509 to 1.x.

fix($markdown): Snippets should allow spaces in file path (closes #1505)

---

packages/@vuepress/core/lib/node/plugin-api/util.js

**Summary**
```js
// vuepress-plugin-foo.js
module.exports = () => {}
```
VuePress should show error and fallback to `{}` when confronted with such situations.
N/A

fix($core): assert object return type for functional plugin

---

packages/@vuepress/core/lib/node/App.js

**Summary**
If we add multiple pages with the same path (i.e. theme has already provided a homepage but we want to override it), VuePress client will break with the following message:
```
[vue-router] Duplicate named routes definition: { name: "v-b2754d56", path: "" }
```
This PR prevent from adding duplicate route. If a duplicate route was to be add, it will override the old one.
You have tested in the following browsers: (Providing a detailed version will be …

feat($core): prevent duplicate route

---

packages/@vuepress/theme-default/components/SidebarLink.vue
packages/@vuepress/theme-default/util/index.js

Credits goes to #1012 
This PR is based on top of master and has no changes in the **Sidebar.vue** file compared to the original.
**Summary**
**before** sidebar is not rendered at all, because of an error
**after** sidebar is rendered with external links properly
See demo: https://hungry-yonath-bfd0a1.netlify.com/ …

fix #764 - support external links in sidebar

---

packages/docs/docs/plugin/option-api.md

Indent closing tag `</div>` at line 429.
**Summary**
Just fix small indent. No related issue found.

docs: fix indent

---

packages/docs/docs/theme/default-theme-config.md

**Summary**
There are users who are making the mistake of trying to integrate Algolia itself rather than the DocSearch. While this is pretty clear if you read the whole …

docs: Enforce consistent naming to reduce confusion

---

__mocks__/vuepress-theme-without-index/index.js
__mocks__/vuepress-theme-without-index/package.json
packages/@vuepress/core/lib/node/__tests__/prepare/App.spec.js
packages/@vuepress/core/lib/node/__tests__/prepare/fixtures/docs-dep-theme-without-index/.vuepress/config.js
packages/@vuepress/core/lib/node/__tests__/prepare/fixtures/docs-dep-theme-without-index/README.md
packages/@vuepress/core/lib/node/loadTheme.js

Fix "ENOTDIR: not a directory" error

---

packages/@vuepress/markdown-loader/index.js
packages/@vuepress/markdown/index.js
packages/@vuepress/markdown/package.json

This reverts commit f04adbf1eaef805736c1aa89a460b29cb59a2b17.
**Summary**
- Before (The TOC rendered correctly):
- After (The TOC rendered correctly): 

Revert "feat($markdown): cache parser (#1359)"

---

packages/@vuepress/core/lib/client/components/Content.js

**Summary**
- Before:
- After:

fix($core): Search result cannot jump to the correct hash anchor (close: #1594)

---

packages/docs/docs/zh/README.md

**Summary**
Update VuePress Chineses doc, in order to match Chinese Typography standards.
For more details: 
If a sentence has Chinese and English mixed, there should be …

docs: add a space between Chinese and English words in zh-cn documentation

---

packages/docs/docs/theme/default-theme-config.md

**Summary**
Updated the docs to reflect changes in v1 in regards too overrides.styl being replaced, as well as Navbar not being available in a custom layout, which seems …

Update default theme config docs to reflect changes in v0 vs v1

---

packages/@vuepress/plugin-medium-zoom/clientRootMixin.js
packages/@vuepress/plugin-medium-zoom/index.js
packages/@vuepress/plugin-medium-zoom/package.json
packages/docs/docs/plugin/official/plugin-medium-zoom.md

**Summary**
Updated `medium-zoom` dependency to recently released v1.0.4 with [custom options](https://github.com/francoischalifour/medium-zoom#options).\
These custom options allow better customization of `medium-zoom` and would be very useful for many users of this plugin.
This update is fully backwards-compatible and does not introduce any bugs by itself.
If adding a …

🔃 Update medium-zoom to v1.0.4

---

packages/@vuepress/core/lib/node/webpack/DevLogPlugin.js

As VSCode makes `http://localhost:8080/)` including trailing parentheses which leads to a 404.
**Summary**
- [] Build-related changes

Remove parentheses around site url

---

packages/docs/docs/config/README.md

the previous link currently gives a 404
**Summary**
The old link looks to have been from 0.x and not updated with the 1.x switch on master. Here's what the change is …

docs: updates default preset hyperlink

---

packages/docs/docs/theme/default-theme-config.md
packages/docs/docs/zh/theme/default-theme-config.md

**Summary**
Service Worker related features have been separated into a standalone plugin @vuepress/plugin-pwa.
Ref: https://v1.vuepress.vuejs.org/miscellaneous/migration-guide.html#serviceworker
To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on …

docs: remove outdated content

---

packages/docs/docs/README.md
packages/docs/docs/guide/getting-started.md
packages/docs/docs/zh/guide/getting-started.md

It seems to point to an older version (1.0.0-rc.1 instead of 1.0.2).
**Summary**

Remove tag 'next' from installation instructions

---

packages/@vuepress/core/lib/client/components/Content.js

**Summary**
**Bug**: example, use `<Content />` in a custom page without markdown, will raise `[Vue warn]: Unknown custom element`, like #1173 #1426
**Reason**: because it not inject any content in `@internal/page-components` while not find markdown file, `Vue.component` of `pageKey` must be `undefined`, then `h(pageKey)` raise this error
**Fix**: judge as `if (Vue.component(pageKey))`, unnecessary to render if no component existed
You have tested in the …

fix: fix 'Unknown custom element' without any content (#1426)

---

packages/@vuepress/core/lib/node/webpack/createBaseConfig.js

**Summary**
Have webpack prioritise the use of vuepress dependencies over the working directories node_modules.
Fixes #1708
Currently if vuepress is used to generate docs for a project depending on the latest version of css-loader `yarn vuepress dev docs` serves a blank screen.
If `package.json` resembles this:
```
{
"scripts": {
"docs:dev": "vuepress dev docs"
},
"dependencies": {
"vuepress": "^1.0.2",
"css-loader": "^3.1.0"
}
}
```
vuepress will serve a blank page with the error: 
```
ValidationError: Invalid options object. CSS Loader has been initialised using an options object that does not match the API schema.
- options has an unknown property 'exportOnlyLocals'. These properties are valid:
```
If changing the UI …

fix #1708 prioritise vuepress dependencies over cwd node_modules

---

packages/@vuepress/plugin-medium-zoom/index.js
packages/docs/docs/plugin/official/plugin-medium-zoom.md
packages/docs/docs/zh/plugin/official/plugin-medium-zoom.md

**Summary**
Disable zoom for links (e.g. "This project is sponsored by bit" on https://v1.vuepress.vuejs.org/guide/).

fix($plugin-medium-zoom): disable zoom for links

---

packages/@vuepress/theme-default/components/SidebarLink.vue
packages/docs/docs/guide/directory-structure.md

Fix sidebarDepth:0 in YAML - fix #1701

---

docs/config/README.md

Fixed wrong preposition in the description for `base` and moved it to the correct place in the sentence. Made a few other minor edits to make this section a little stronger.
**Summary**
- [] Chrome
To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working …

Fixed some of the sentence structure

---

packages/@vuepress/theme-default/util/index.js

Little improvement for vuejs#1677
I think we can use any custom protocol for external link.

 fix(Util): use any custom protocol for outboundRE

---

docs/guide/basic-config.md

"They" had been misspelled as "The" in the vue press documentation and this has been corrected in this fix.
**Summary**
None

fix: #1797 Corrected the typo

---

packages/docs/docs/plugin/official/plugin-pwa.md
packages/docs/docs/zh/plugin/official/plugin-pwa.md

**Summary**
Improve pwa-plugin doc by adding an example of a fully PWA-compliant config for pwa-plugin.
Need translation for zh.

doc: add an example of a fully PWA-compliant config for pwa-plugin

---

lerna.json
package.json
packages/docs/docs/.vuepress/nav/en.js
packages/docs/docs/.vuepress/nav/zh.js
packages/docs/docs/miscellaneous/local-development.md
packages/docs/docs/zh/miscellaneous/local-development.md

**Summary**
When I started to local dev i face some issues with links and just where to start. So i tried to add a simple doc for it and describe use cases. I hope it …

docs(dev): adding doc to local development and add more script

---

packages/@vuepress/core/lib/node/webpack/createBaseConfig.js

**Summary**
Didn't have the time to get a minimal reproduction, but here's the error log I've got after upgrading to vuepress 1.0.3: …

fix($core): do not transpile core packages' dependencies

---

packages/@vuepress/theme-default/components/Page.vue
packages/@vuepress/theme-default/package.json
packages/docs/docs/theme/default-theme-config.md
yarn.lock

feat: Disable next and prev links from global config

---

CHANGELOG.md

chore(changelog): add changelog to v1.0.4

---

packages/docs/docs/guide/permalinks.md

**Summary**
Fixes a typo in the permalinks section of the guide.  Changes "link root" to "link rot".  The Wikipedia link next to the phrase goes to the "link rot" page.
Fixes #1813 
**Other …

docs: Fix typo in  permalinks.md fix #1813

---

.circleci/config.yml
package.json
packages/@vuepress/theme-default/components/SidebarLink.vue
packages/docs/docs/miscellaneous/local-development.md

**Summary**
Fix #1748
New CI workflow introduced in this PR:
Improving CI process

Improve CI process

---

packages/docs/docs/guide/deploy.md

**Summary**
The Travis script is missing `npm install` which means Travis will show:
> vuepress build docs
sh: 1: vuepress: not found

fix: Add `npm install`

---

packages/@vuepress/core/lib/node/dev/index.js

**Summary**
```js
this.pagesWatcher = chokidar.watch([
'**/*.md',
'.vuepress/components/**/*.vue'
], {
cwd: this.context.sourceDir,
ignored: ['.vuepress/**/*.md', 'node_modules'],
ignoreInitial: true
})
```
Because the glob patterns end with`*.md` and `*.vue`, `addDir` and `unlinkDir` will never be triggered, right?
If adding a **new feature**, the PR's description …

refactor($core): stop watching unnecessary events

---

packages/@vuepress/plugin-search/SearchBox.vue
packages/@vuepress/theme-default/components/AlgoliaSearchBox.vue
packages/docs/docs/theme/default-theme-config.md

**Summary**
Add search-box placeholder option to the config file
closes #1650 

feat($theme): Add search box placeholder setting to theme-config

---

packages/@vuepress/theme-default/components/Navbar.vue

**Summary**
- [ x] Bugfix
- [ x] No
- [ x] Chrome

fix($theme-default): add text ellipsis to navbar (#1683)

---

packages/@vuepress/plugin-last-updated/index.js

**Summary**
When using a Git submodule, the "last updated" time for all files within that submodule is incorrect.
This happens because the `git log` command, when operating from a working directory that is part of the parent repository, only operates on that parent repository. As a result, any query for the log for a specific file that is located in a submodule will return the log for the submodule entry itself.
So, for example, if we have a submodule `/foo` and a file `/foo/bar.md`, then even if `bar.md` was last updated many years ago, if we commited a update of the submodule five minutes ago that will cause Vuepress to show that `bar.md` was last updated 5 minutes ago, while in fact it hasn't.
This pull request resolves this bug by first changing the current working directory to the …

fix($last-updated): use file author time instead of submodule commit time (1.x)

---

lib/prepare/util.js

**Summary**
When using a Git submodule, the "last updated" time for all files within that submodule is incorrect.
This happens because the `git log` command, when operating from a working directory that is part of the parent repository, only operates on that parent repository. As a result, any query for the log for a specific file that is located in a submodule will return the log for the submodule entry itself.
So, for example, if we have a submodule `/foo` and a file `/foo/bar.md`, then even if `bar.md` was last updated many years ago, if we commited a update of the submodule five minutes ago that will cause Vuepress to show that `bar.md` was last updated 5 minutes ago, while in fact it hasn't.
This pull request resolves this bug by first changing the current working directory to the …

fix($last-updated): use file author time instead of submodule commit time (0.x)

---

packages/@vuepress/core/lib/node/Page.js
packages/@vuepress/core/lib/node/__tests__/prepare/Page.spec.js
packages/docs/docs/plugin/option-api.md

**Summary**
**There is no dedicated documentation for async options for now**
I am working on a project where I use vuepress alpha.47. I am trying to fetch dynamically …

feat(options): make enhancers async ready without breaking changes

---

packages/docs/docs/guide/deploy.md

fix: Add `npm ci` instructions for Travis CI.

---

packages/@vuepress/plugin-search/SearchBox.vue
packages/@vuepress/plugin-search/index.js
packages/docs/docs/plugin/official/plugin-search.md

**Summary**
Adds hotkey to focus SearchBox component with configurable keys, defaulting to `s` and `/`.
This makes it much easier to switch to the docs and focus the searchbox when using documentation in tandem with programming. Sites like [docs.rs](https://docs.rs/) and even GitHub itself support this behavior. 
Fixes #624

feat($plugin-search): Add support for search hotkeys

---

packages/@vuepress/theme-default/__tests__/components/DropdownLink.spec.js
packages/@vuepress/theme-default/__tests__/components/__snapshots__/DropdownLink.spec.js.snap
packages/@vuepress/theme-default/components/DropdownLink.vue
packages/@vuepress/theme-default/components/NavLink.vue
packages/@vuepress/theme-default/components/NavLinks.vue
packages/@vuepress/theme-default/components/Navbar.vue
packages/docs/docs/.vuepress/config.js
packages/docs/docs/.vuepress/nav/en.js
packages/docs/docs/.vuepress/nav/zh.js
packages/docs/docs/guide/i18n.md
packages/docs/docs/theme/default-theme-config.md
packages/docs/docs/zh/guide/i18n.md
packages/docs/docs/zh/theme/default-theme-config.md

**Summary**
Hi !
I've edited the accessibility of items on the navbar. (for  this issue https://github.com/vuejs/vuepress/issues/1818 )

fix($theme-default): Make navbar dropdown links accessible

---

CHANGELOG.md

**Summary**
Remove duplicate version in changelog

fix($changelog): Remove duplicate version in changelog

---

packages/docs/docs/plugin/official/plugin-google-analytics.md

The `next` flag seems like an artifact for those who are not on the latest VuePress. Since we are on VuePress 1.0, this should not be the default install path
**Summary**
**Other …

docs: Remove next recommendation

---

packages/@vuepress/theme-default/index.js

**Summary**
**V0**
**Regression**
**After this patch**
This regression was introduced by #1462:
https://github.com/vuejs/vuepress/pull/1462/files#diff-89632cc75524a98d72bf12ae77132560R24-R41

fix($theme-default): regression of custom container default title

---

packages/@vuepress/shared-utils/src/getPermalink.ts

**Summary**
relevant to #1783
`:regular` is different with all the other template variables(only `:regular` can't go before a slash).
Besides, I found VuePress can't work fine if someone config like below(although It‘s a meaningless config), and this PR will also solve this problem:
```
permalink: ":regular"
};
```
If adding a **new feature**, the PR's …

feat($shared-utils): remove leading slash of regularPath when getting permalink

---

packages/@vuepress/plugin-active-header-links/clientRootMixin.js
packages/@vuepress/plugin-active-header-links/package.json
packages/@vuepress/theme-default/index.js
packages/@vuepress/theme-default/package.json
packages/docs/docs/.vuepress/config.js
packages/docs/docs/theme/default-theme-config.md
packages/docs/docs/zh/theme/default-theme-config.md
yarn.lock

**Summary**
The reason of changing `throttle` to `debounce` is to avoid [this issue](https://github.com/vuepress/vuepress-plugin-smooth-scroll/issues/1).

feat($theme-default): smooth scroll (close #567)

---

packages/vuepress/README.md

Fixed #1908.
**Summary**
The README file was created based on <https://www.makeareadme.com/>

docs: Add a README to vuepress package

---

packages/@vuepress/theme-default/components/PageNav.vue

**Summary**
This fixes a minor UI regression of PR #1427, which I reported as an inline-comment [here](https://github.com/vuejs/vuepress/commit/6b5a00208a32560cbfab50be23698386d4ce5315#r35089278).
**Before (v1.1.0)**:
**After (same as v1.0.4)**:
To avoid wasting your time, it's best to open a **feature request …

fix($theme-default): make arrow spacing consistent

---

packages/@vuepress/core/lib/node/theme-api/index.js

**Summary**
When layout is not present in a theme, the following shows up in console:
```
tip Apply theme vuepress-theme-.vuepress (extends vuepress-theme-vuepress-theme) ...
TypeError: Cannot read property 'path' of undefined
at ThemeAPI.getLayoutComponentMap (@vuepress\core\lib\node\theme-api\index.js:83:67)
at ThemeAPI.init (@vuepress\core\lib\node\theme-api\index.js:35:36)
at new ThemeAPI (@vuepress\core\lib\node\theme-api\index.js:17:10)
at loadTheme (@vuepress\core\lib\node\loadTheme.js:59:10)
at App.process (@vuepress\core\lib\node\App.js:100:21)
at dev (@vuepress\core\lib\index.js:14:13)
at args (vuepress\lib\util.js:35:12)
at CAC.cli.command.option.option.option.option.option.option.option.option.option.action (vuepress\lib\registerCoreCommands.js:38:23)
at CAC.runMatchedCommand …
```

fix($core): `cannot read property 'path' of undefined`

---

packages/@vuepress/theme-default/components/DropdownLink.vue

**Summary**
#1837 convert dropdown-title from `a` to `button`, which brings inconsistent ui between nav-link and dropdown-title.(Especially on the phone)

fix($theme-default): make dropdown-title's UI consistent with nav-link

---

packages/docs/docs/guide/using-vue.md

As someone relatively new to JS + Vue, the existing sample code for dynamic imports didn't tell me how to actually register the component dynamically, which is the likely case for importing a module.
The proposed code block does both: it dynamically imports the module and also registers the component.
**Summary** …

Code block to dynamically register a component

---

packages/docs/docs/zh/guide/deploy.md
packages/docs/docs/zh/guide/using-vue.md
packages/docs/docs/zh/miscellaneous/local-development.md
packages/docs/docs/zh/plugin/official/plugin-google-analytics.md
packages/docs/docs/zh/theme/option-api.md

 feat($docs): Sync changes in Chinese & Translate docs-'local development'

---

packages/@vuepress/core/lib/node/App.js

**Summary**
Since `process` was already an async function, and process is the only function which uses `resolveConfigAndInitialize`, which is the only function to use …

fix 1185, feat:  support async function exported in vuepress config

---

packages/@vuepress/theme-default/components/Page.vue
packages/@vuepress/theme-default/components/PageEdit.vue
packages/@vuepress/theme-default/components/PageNav.vue

**Summary**
Use stylus instead of native css in style tag of default-theme.
A few of default-theme components `<style>` tag are mixed by native CSS and stylus. IMHO should use the same style. …

refactor($theme-default): use stylus instead of native css in style tag

---

packages/@vuepress/markdown/lib/snippet.js

fix($markdown): notify error when not found snippet #1872

---

packages/@vuepress/theme-default/components/NavLink.vue
packages/docs/docs/theme/default-theme-config.md
packages/docs/docs/zh/theme/default-theme-config.md

feat($theme-default): support configuring target and rel for nav links (close #1353)

---

packages/docs/docs/theme/default-theme-config.md
packages/docs/docs/zh/theme/default-theme-config.md

docs($theme-default): add version badge to smooth-scroll (close #1930)

---

packages/@vuepress/theme-default/components/DropdownLink.vue

**Summary**
Fix #1948 
Logic is a little complicated here. Someone please do test this again.
When people use tab to focusout the last item, the dropdown-links should be closed since the `open` class is surely  active.
When people use mouse to focusout the last item, however, the `open` class may not be active.
To …

fix($theme-default): close dropdown-links when focusout on the last item (close #1948)

---

docs/default-theme-config/README.md
docs/zh/default-theme-config/README.md
lib/app/components/Badge.vue
lib/default-theme/styles/config.styl

**Summary**
Allow badge colors to be overridden via https://vuepress.vuejs.org/default-theme-config/#simple-css-override
n/a

feat($config): Allow override of badge colors

---

packages/@vuepress/core/lib/node/App.js
packages/@vuepress/core/lib/node/Page.js
packages/@vuepress/core/lib/node/webpack/createBaseConfig.js
packages/@vuepress/markdown-loader/index.js
packages/@vuepress/theme-default/components/SidebarLink.vue
packages/docs/docs/theme/default-theme-config.md

**Summary**
Fix #1903
**Indentation when extracting subheaders (h3, h4, h5, h6):**
Add an extractHeaders option.

feat($markdown): `extractHeaders` option (close: #1903)

---

packages/@vuepress/shared-utils/src/slugify.ts

**Summary**
This adds `“` `”` `‘` `’` to the list of characters that convert to `-` in links. If there are any sites with existing headings that contain those characters, their links will change, potentially resulting in broken links. On the other hand, links that include those characters can behave unpredictably, so they wouldn't have been perfectly working links to begin with.
You have tested in the following browsers: (Providing a detailed version will be …

fix($shared-utils): Add curly quotes to rSpecial

---

packages/docs/docs/config/README.md
packages/docs/docs/theme/default-theme-config.md
packages/docs/docs/zh/config/README.md

**Summary**
Move `markdown.extractHeader` documentation in the right section (config).

docs: move extractHeader documentation to the right section

---

packages/@vuepress/theme-default/components/SidebarLink.vue

**Summary**
I realized deep sidebar links rendering was not working as expected.
Before fix:
After fix:
The sidebar links rendering code seems a bit complex, I'll try to refactor to make it more readable later.
To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval …

fix($default-theme): Fix deep sidebar links rendenring

---

packages/@vuepress/core/lib/client/style/config.styl
packages/@vuepress/theme-default/global-components/Badge.vue
packages/docs/docs/config/README.md
packages/docs/docs/zh/config/README.md

feat($config): Allow overriding badges colors (close #1940)

---

packages/docs/docs/zh/theme/default-theme-config.md

**Summary**
Reference to #1974 

docs($cn): add Navbar Logo section for Default Theme Config

---

packages/docs/docs/plugin/using-a-plugin.md

Update to use triple `xxx` instead double `xx`, for consistency in all examples.
All examples has triple `x`, but this had double.
**Summary**

Improve file using-a-plugin.md for consistency

---

packages/@vuepress/markdown/lib/highlight.js

Currently, code from Rust files is not being highlighted. This can be resolved by mapping the Rust file ending to the name.

feat($markdown): Support for Rust file extension

---

packages/docs/docs/guide/deploy.md
packages/docs/docs/guide/getting-started.md
packages/docs/docs/miscellaneous/local-development.md

fix($docs): Fixed typo (#1997)

---

packages/docs/docs/plugin/official/plugin-active-header-links.md
packages/docs/docs/plugin/official/plugin-back-to-top.md
packages/docs/docs/plugin/official/plugin-medium-zoom.md
packages/docs/docs/plugin/official/plugin-nprogress.md
packages/docs/docs/plugin/official/plugin-pwa.md
packages/docs/docs/plugin/official/plugin-register-components.md
packages/docs/docs/plugin/official/plugin-search.md
packages/docs/docs/zh/plugin/official/plugin-active-header-links.md
packages/docs/docs/zh/plugin/official/plugin-back-to-top.md
packages/docs/docs/zh/plugin/official/plugin-medium-zoom.md
packages/docs/docs/zh/plugin/official/plugin-nprogress.md
packages/docs/docs/zh/plugin/official/plugin-pwa.md
packages/docs/docs/zh/plugin/official/plugin-register-components.md
packages/docs/docs/zh/plugin/official/plugin-search.md

**Summary**
Official plugins install with `@next` tag stop to get the latest version

docs: Remove @next tag in official plugins

---

packages/docs/docs/zh/guide/markdown.md

`Emoji -> A list of all emojis available can be found here.` is missing in zh translation.
**Summary**

docs: fix missing translation of Zh.

---

packages/@vuepress/core/lib/index.js
packages/@vuepress/core/lib/node/App.js
packages/@vuepress/core/lib/node/build/index.js

fix($core): set NODE_ENV before creating app

---

packages/docs/docs/config/README.md
packages/docs/docs/zh/config/README.md

The correct link is https://ssr.vuejs.org/zh/api/#shouldprefetch, but it's present as https://ssr.vuejs.org/zh/api/#shouldpreload now.
**Summary**
as above.

docs: fix misleading shouldPrefetch link

---

packages/@vuepress/plugin-google-analytics/enhanceAppFile.js

Fixes #2017
Reasoning in [Issue](https://github.com/vuejs/vuepress/issues/2017#issuecomment-558530592).

fix($plugin-pwa): duplicate tracking of first page (fix #2017)

---

packages/@vuepress/core/lib/node/App.js

fix($core): temp option in siteConfig has not effect (fix #2038)

---

packages/@vuepress/theme-default/components/AlgoliaSearchBox.vue

**Summary**
Fix #1929 
Fix #1802 
Fix algolia search route is not correct in the case that `$site.base` is not `/`.
For example, in [my project documention](https://www.sigure.xyz/shoeprint-recognition/), I search some keywords, it will route to `https://www.xxx.com/$site.base/$size.base/path/to/page/#hash` rather than `https://www.xxx.com/$site.base/path/to/page/#hash`, `$site.base` is repeat.
You have tested in the following browsers: (Providing a detailed …

fix($theme-default): wrong algolia search route with base config

---

packages/@vuepress/theme-default/index.js
packages/@vuepress/theme-default/styles/custom-blocks.styl
packages/docs/docs/guide/markdown.md
packages/docs/docs/zh/guide/markdown.md

feat($theme-default): markdown details custom block (close #768)

---

packages/@vuepress/plugin-pwa/index.js

**Summary**
Disable `updatePopup` in `config.js`:
```js
['@vuepress/pwa', {
updatePopup: false
}],
```
`index.html` that generated by `build`:
```html
<div class="global-ui"><SWUpdatePopup></SWUpdatePopup></div>
```
`index.html` that generated by `build`:
```html
<div class="global-ui"></div>
```

fix($plugin-pwa): no global-ui-component when updatePopup is disabled

---

packages/@vuepress/theme-default/components/Home.vue
packages/docs/docs/theme/default-theme-config.md
packages/docs/docs/zh/theme/default-theme-config.md

feat($theme-default): allow optional subtitle

---

packages/docs/docs/guide/getting-started.md

docs: create project folder in global installation (close #2045)

---

packages/docs/docs/plugin/README.md
packages/docs/docs/plugin/official/plugin-active-header-links.md
packages/docs/docs/zh/plugin/README.md
packages/docs/docs/zh/plugin/official/plugin-active-header-links.md
packages/docs/docs/zh/plugin/official/plugin-medium-zoom.md

**Summary**
Ref: #2033 
Will finish the Chinese translation after reviewed.

docs: refine plugin documentation

---

packages/@vuepress/shared-utils/src/moduleResolver.ts

**Summary**
because of the default value returned by `resolveScopePackage`, I remove the check.

feat: remove unnecessary check in moduleResolver.ts

---

packages/docs/docs/guide/markdown.md
packages/docs/docs/guide/using-vue.md
packages/docs/docs/theme/inheritance.md
packages/docs/docs/zh/guide/markdown.md
packages/docs/docs/zh/guide/using-vue.md
packages/docs/docs/zh/theme/inheritance.md

**Summary**
Fix #2080 
I replaced `warn` by `warning` everywhere to be consistent with custom containers `warning` value.

docs: update badge documentation

---

packages/@vuepress/core/lib/client/style/config.styl
packages/@vuepress/theme-default/components/Home.vue
packages/docs/docs/config/README.md
packages/docs/docs/zh/config/README.md

**Summary**
Fix: #2055 
It took me a while to realize that `palette.styl` can do more than only color. The naming seems to be out-dated?

feat: add variable to config HomePage width (close #2055)

---

packages/docs/docs/guide/basic-config.md
packages/docs/docs/zh/guide/basic-config.md

**Summary**
https://github.com/vuejs/vuepress/blob/7a09a725928206260e9aed1b6b16960f09da20f2/packages/%40vuepress/core/lib/client/app.js#L95

docs: add missing isServer in app level enhancements

---

packages/vuepress/lib/handleUnknownCommand.js

Ignore node_modules in multi-layer catalogue in inferUserDocsDirectory
**Summary**
inferUserDocsDirectory There is a pattern to ignore node_modules for globby in …

fix($cli): inferUserDocsDirectory ignore all node_modules

---

packages/@vuepress/core/lib/node/dev/index.js
packages/@vuepress/core/lib/node/webpack/DevLogPlugin.js
packages/docs/docs/api/cli.md
packages/docs/docs/zh/api/cli.md
packages/vuepress/package.json
yarn.lock

**Summary**
please head #2100.

feat($cli): run debug mode without clearing screen (close #2100)

---

packages/docs/docs/.vuepress/config.js
packages/docs/docs/plugin/official/plugin-blog.md
packages/docs/docs/theme/blog-theme.md
packages/docs/docs/zh/plugin/official/plugin-blog.md
packages/docs/docs/zh/theme/blog-theme.md

**Summary**
The WIP status has just been removed.
As they are official plugin and theme, It probably should be mentioned in documentation. The content is distilled from README.md, if you have any better idea to introduce them, please leave your comment. 
To avoid wasting your time, it's best to open a **feature …

docs: official blog plugin and theme

---

.all-contributorsrc
README.md
package.json

docs: update README content and focus on core team

---

packages/@vuepress/core/lib/client/app.js
packages/@vuepress/core/lib/client/clientEntry.js
packages/@vuepress/core/lib/client/serverEntry.js
packages/docs/docs/guide/basic-config.md
packages/docs/docs/zh/guide/basic-config.md

feat($core): support async enhanceApp (close #2074)

---

packages/@vuepress/core/lib/client/style/config.styl

**Summary**
close #2127
In fact, it's not a bug, but something can be enhanced.

fix($core): use stylus conditional assignment (close #2127)

---

packages/@vuepress/core/lib/node/webpack/createBaseConfig.js

**Summary**
Related to #1771 
Fix #1606 
Fix #1990 
**Before**
```js
// WRONG
/(@vuepress|vuepress-)\/^((?!node_modules).)*\.js$/.test('/a/b/@vuepress/core/lib/index.js')
// false
// CORRECT
/(@vuepress|vuepress-)\/^((?!node_modules).)*\.js$/.test('/a/b/@vuepress/core/node_modules/xxx/index.js')
// false
// WRONG
/(@vuepress|vuepress-)\/^((?!node_modules).)*\.js$/.test('/a/b/vuepress-plugin-xxx/lib/index.js')
// false
// CORRECT
/(@vuepress|vuepress-)\/^((?!node_modules).)*\.js$/.test('/a/b/vuepress-plugin-xxx/node_modules/xxx/index.js')
// false
```
**After**
```js
// CORRECT
/(@vuepress\/[^\/]*|vuepress-[^\/]*)\/(?!node_modules).*\.js$/.test('/a/b/@vuepress/core/lib/index.js')
// true
// CORRECT
/(@vuepress\/[^\/]*|vuepress-[^\/]*)\/(?!node_modules).*\.js$/.test('/a/b/@vuepress/core/node …
```

fix($core): transpile vuepress packages and md files (close #1606)(close #1990)

---

packages/vuepress/package.json

**Summary**
The `true` command does not exist on Windows so a failure of the `opencollective-postinstall` command would lead to an unintentional failure of the `postinstall` script.
**Other …

fix: opencollective-postinstall failure not being ignored on Windows

---

packages/@vuepress/plugin-last-updated/index.js
packages/docs/docs/plugin/official/plugin-last-updated.md

**Summary**
It adds a new option to `defaultTransformer` in `plugin-last-updated` . 
I think it's a good way  to use the `toLocaleString` options argument to format the timestamp
**Other …

feat($plugin-last-updated): add dateOptions to options (close #2168)

---

.github/CONTRIBUTING.md
README.md

**Summary**
Anyone help finish `Testing Setup`? And I'm not sure what's the relation between CONTRIBUTING.md and the [Local Development](https://vuepress.vuejs.org/miscellaneous/local-development.html) in the document site. …

docs: update CONTRIBUTING and README

---

packages/docs/docs/api/cli.md
packages/vuepress/lib/checkEnv.js

**Summary**
1. Refine cli documentation
2. Update comments in `checkEnv.js`
Will update Chinese doc after review
**Best wishes to all those fighting the coronavirus in China and all over the …

docs: refine cli documentation

---

packages/@vuepress/test-utils/lib/createJestRunner.js
scripts/test.js

**Summary**
`yarn test` will run every tests in all workspaces.
When I looked at the source code, I found that there's an option to test a specific package:
```js
// scripts/test.js
if (args.p) {
const packages = (args.p || args.package).split(',').join('|')
regex = `.*@vuepress/(${packages}|plugin-(${packages}))/.*\\.spec\\.(js|ts)$`
const i = rawArgs.indexOf('-p')
rawArgs.splice(i, 2)
}
const jestRunner = createJestRunner([
'--config', 'scripts/jest.config.js',
'--runInBand',
...(regex ? [regex] : [])
], rawArgs)
```
But when I ran `yarn test -p core`, it failed with `ReferenceError: core is not defined`.
I tracked down `createJestRunner` and found it is caused by #1404.
The `rawArgs` is supposed to contain `'--inspect-brk'`, but it will also contain`'-p'` and `'core'` if I run `yarn …

fix: fail to test specific package

---

packages/@vuepress/core/lib/node/Page.js
packages/@vuepress/core/lib/node/__tests__/prepare/Page.spec.js
packages/@vuepress/core/lib/node/build/index.js

**Summary**
These optimisations make sense on projects that contains a huge amount of pages to render. 
Related to #1560 
Performance enhancement
**Steps:**
[Improvement #1](https://github.com/vuejs/vuepress/commit/9dce83575a8e798ee29fa8ddedacfdfbbb3e7ac6) : Render static pages in parallel instead of rendering one page after the other.
[Improvement #2](https://github.com/vuejs/vuepress/pull/2163/commits/cbe1af0b674d209beedb91c7a4692effc3118d5a) : Run extendPageData enhancers in parallel

feat($core): Improve VuePress build time

---

packages/docs/docs/zh/config/README.md

**Summary**
- fix error link about sass-loader in zh docs.(en docs is right)
[sass | en](https://vuepress.vuejs.org/config/#sass)
[sass | zh](https://vuepress.vuejs.org/zh/config/#sass) …

docs($zh): fix sass-loader link

---

packages/@vuepress/theme-default/util/index.js

This arbitrarily logged out when nesting was greater than 3.
```
07:58:13.598 [vuepress] detected a too deep nested sidebar group. 2 2.258cb917.js:1:3364
```
https://github.com/vuejs/vuepress/issues/2190
**Summary**
N/A
N/A …

fix($theme-default): remove error logs for nested sidebar groups

---

packages/@vuepress/plugin-pwa/lib/enhanceAppFile.js
packages/@vuepress/plugin-pwa/package.json
yarn.lock

**Summary**
close #2222
It's caused by https://github.com/yyx990803/register-service-worker/pull/33 , which references `window.addEventListener` in the outer scope.

fix($plugin-pwa): work with register-service-worker 1.7.0 (close #2222)

---

packages/@vuepress/core/lib/client/index.ssr.html
packages/@vuepress/core/lib/client/root-mixins/updateMeta.js
packages/@vuepress/core/lib/node/App.js
packages/@vuepress/core/lib/node/build/index.js

**Summary**
leave meta tags updating to [updateMeta.js](https://github.com/vuejs/vuepress/blob/master/packages/%40vuepress/core/lib/client/root-mixins/updateMeta.js)
fix #777 , relate to #2153 
To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on …

fix: duplicate meta tags

---

packages/docs/docs/theme/inheritance.md

Fix broken link for `globalLayout` in theme -> **Inheritance Strategy** section
**Summary**

docs: fix broken link for globalLayout

---

packages/docs/docs/zh/guide/deploy.md

**Summary**
Wrong command line for Netlify

docs($zh): fix wrong command in deploy guide

---

packages/@vuepress/plugin-search/match-query.js

**Summary**
Close #2242
- If the query only has ASCII chars, treat it as English (keep current match algorithms)
- If the query has non-ASCII chars, treat is as other languages (fallback to use `indexOf` as before)
Related to #1557

fix($plugin-search): match non-ASCII chars (close #2242)

---

packages/docs/docs/miscellaneous/design-concepts.md
packages/docs/docs/zh/miscellaneous/design-concepts.md

**Summary**
The docs were referring to `theme/config.js` when it was meant to be `theme/index.js`.
Hope it helps clarify that.

docs: Correctly refer to theme/index.js file

---

packages/@vuepress/shared-utils/src/moduleResolver.ts

**Summary**
Close #2286
For non-scoped modules, the `prefixSlicePosition` should not have `org.length + 1`

fix($shared-utils): fail to resolve markdown-it plugins (close #2286)

---

packages/@vuepress/theme-default/components/DropdownLink.vue

fix($theme-default): close dropdown on mouseout (fix #2227)

---

packages/@vuepress/theme-default/components/DropdownLink.vue

revert: "fix($theme-default): close dropdown on mouseout (fix #2227)"

---

packages/docs/docs/zh/plugin/official/plugin-register-components.md

修正了使用选项时注册插件的示例用法，对componentsDir中的somepath进行了示例说明
**Summary**

docs($zh): fix plugin-register-components.md example error

---

packages/@vuepress/core/lib/node/webpack/createBaseConfig.js

**Summary**
This change passes the list of entry files into the options of `@vue/babel-preset-app`.
I spent some time looking at #1168 and this is what I found out: …

fix($core): include polyfills correctly (close #1168)

---

packages/@vuepress/markdown/__tests__/__snapshots__/snippet.spec.js.snap
packages/@vuepress/markdown/__tests__/fragments/code-snippet-with-indented-region.md
packages/@vuepress/markdown/__tests__/fragments/code-snippet-with-region-and-highlight.md
packages/@vuepress/markdown/__tests__/fragments/code-snippet-with-region-and-single-highlight.md
packages/@vuepress/markdown/__tests__/fragments/code-snippet-with-region.md
packages/@vuepress/markdown/__tests__/fragments/snippet-with-indented-region.html
packages/@vuepress/markdown/__tests__/fragments/snippet-with-region.js
packages/@vuepress/markdown/__tests__/snippet.spec.js
packages/@vuepress/markdown/lib/snippet.js
packages/docs/docs/guide/markdown.md

Only import a portion of a code file delimited by [VS Code custom regions markers](https://code.visualstudio.com/docs/editor/codebasics#_folding), based on the region key you set via a fragment identifier (`#`):
_<project root>/docs/hello-world.md_
```md
<<< @/src/hello-world.js#function-def{1-2}
```
_<project root>/src/hello-world.js_:
```js
// #region function-def
function helloWorld () {
// ..
}
// #endregion function-def
export default helloWorld
```
Contents presented with Vuepress (documentation, tutorials, etc.) may (often?) be related to some "real" projects. Ensuring the code snippets in the doc and the "real" code is very important for this use case. Yet, it can be difficult, or even impossible, to split each code sample in a dedicated file. Therefore, some misleading code lines …

feat(markdown): snippet partial import

---

packages/@vuepress/markdown-loader/package.json
packages/@vuepress/markdown/package.json
packages/@vuepress/plugin-active-header-links/package.json
packages/@vuepress/plugin-back-to-top/package.json
packages/@vuepress/plugin-google-analytics/package.json
packages/@vuepress/plugin-last-updated/package.json
packages/@vuepress/plugin-medium-zoom/package.json
packages/@vuepress/plugin-nprogress/package.json
packages/@vuepress/plugin-pwa/package.json
packages/@vuepress/plugin-register-components/package.json
packages/@vuepress/plugin-search/package.json
packages/@vuepress/shared-utils/package.json
packages/@vuepress/test-utils/package.json
packages/@vuepress/theme-default/package.json
packages/@vuepress/theme-vue/package.json
scripts/bootstrap.js

**Summary**
`homepage` link is error in packages/@vuepress/${pkg}/package.json
Example: Click the [@vuepress/theme-default](https://www.npmjs.com/package/@vuepress/theme-default) homepage link to visit page 404
- [x ] Bugfix
- [x ] No
To avoid wasting your time, it's best to open a **feature request issue** first …

fix: correct homepage URLs in package.json

---

packages/docs/docs/plugin/official/plugin-last-updated.md

According to https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString
it should be `hour12` instead of `hours12`
**Summary**

docs: corrected a typo in the plugin docs

---

packages/docs/docs/guide/getting-started.md
packages/docs/docs/zh/guide/getting-started.md

**Summary**
Hi guys, I wrote a draft to close #2111 , what do you think?
I took the liberty of not recommend globally install VuePress, hope it's expected

docs: refine getting started (close #2111)

---

packages/@vuepress/core/lib/client/root-mixins/updateMeta.js

**Summary**
@chriscdn opened this https://github.com/vuepressjs/vuepress-theme-blog/issues/78, he is having an issue with `<meta>` trying to be removed from `document.head` whereas they where not `document.head`'s children.
This can happens when you use `<meta>` in `<body>` for microdatas. This is automatically done by the blog plugin since https://github.com/vuepressjs/vuepress-theme-blog/pull/64.
After the fix, _global_ `<meta>` and `<meta>` in `<body>` are still at the good place: 
**The PR …

fix($core): check if meta is from head before removing it

---

packages/docs/docs/zh/plugin/official/plugin-last-updated.md

**Summary**
Add missing `dateOptions` for `last-updated` plugin in Chinese documentation.

docs: add missing `dateOptions` for `last-updated` plugin

---

packages/docs/docs/guide/frontmatter.md

**Summary**
Failed to figure out in the docs about how to use the frontmatter variables. After trying `{{$frontmatter}}`, I guessed out it myself. It should save me an hour if the doc tells me how to invoke the variables …

Add hint about how to use variables

---

packages/docs/docs/guide/getting-started.md

Fixing a very minor typo
**Summary**

docs: Fixed a typo in getting-started.md

---

packages/@vuepress/markdown/__tests__/__snapshots__/snippet.spec.js.snap
packages/@vuepress/markdown/__tests__/fragments/code-snippet-highlightLines-single-and-multiple.md
packages/@vuepress/markdown/__tests__/snippet.spec.js
packages/@vuepress/markdown/lib/snippet.js

**Summary**
When importing code snippets with the `<<<` syntax, you could only either specify a single range (`{34-37}`) or a maximum of two lines to be highlighted (`{3,6}`).
This PR fixes the regex that was matching the syntax so it allows for unlimited line highlights like the ` ``` ` syntax.
To avoid wasting …
```

fix($markdown): line highlighting not working correctly when importing code snippets

---

packages/docs/docs/guide/markdown.md
packages/docs/docs/zh/guide/markdown.md

**Summary**
I've kind of ran out of ideas for the code snippet, so if you have any suggestions feel free to comment down below 😃

docs($markdown): add missing examples for line highlighting (fix #2473)

---

packages/docs/docs/miscellaneous/local-development.md

docs: update contributing guide

---

.github/CONTRIBUTING.md
scripts/test.js

docs: update CONTRIBUTING.md

---

.dependabot/config.yml

**Summary**
PS. I've set the default reviewer to me, but it can be anyone from the core team.
// cc @bencodezen, @ulivz

build(deps): add dependabot configuration

---

packages/@vuepress/theme-default/components/NavLink.vue
packages/docs/docs/theme/default-theme-config.md

**Summary**
Currently it's not possible to specify that there should be no `rel` attribute on external nav links to use the default behavior. Setting to an empty string, as [indicated in the documentation](https://v1.vuepress.vuejs.org/theme/default-theme-config.html#navbar-links), is falsy, so you end up in the final ternary, which uses `noopener noreferrer` for external links.
This change allows devs to pass in a falsy, non-`undefined`, value to the `rel` property to have no rel attribute on the link. It also change the fallback of an empty string to `null` since an empty `rel` attribute has no particular meaning, so it's better to have it not there at all.
If changing the UI of default theme, please provide the …

fix: allows no rel attribute on external links in the nav

---

packages/@vuepress/theme-default/components/PageEdit.vue

**Summary**
On the `.last-updated .time` element, the **color contrast is too low** which raised an accessibility warning in a Lighthouse report.
Here is a minor tweak of the color to fix that.
It won't affect much the end user, but provides:
- a more accessible website :tada: 
- a better lighthouse accessibility score by default :ok_hand: 
Style
| | Before | After |
|-|-|-|
|Screenshot | ![Screenshot from 2020-04-05 19-21-41](https://user-images.githubusercontent.com/1302282/78505459-f135ca00-7773-11ea-9723-09613499cd4e.png) | ![Screenshot from 2020-04-05 19-22-18](https://user-images.githubusercontent.com/1302282/78505466-fabf3200-7773- …

fix($theme-default): improve last-updated text color contrast

---

packages/@vuepress/shared-utils/package.json

**Summary**
`toml` is used in `packages/@vuepress/shared-utils/src/parseFrontmatter.ts` but `@vuepress/shared-utils` does not have `toml` as dependencies. This cause `@vuepress/markdown` not reusable outside vuepress.

fix(shared-utils): add toml to shared-utils dependencies

---

packages/@vuepress/theme-default/components/SidebarGroup.vue
packages/@vuepress/theme-default/components/SidebarLinks.vue
packages/@vuepress/theme-default/util/index.js
packages/docs/docs/theme/default-theme-config.md
packages/docs/docs/zh/theme/default-theme-config.md

**Summary**
Adds an optional property for sidebar groups, so that one can initially display a group other than the first as open. Also allows to initially display all groups as closed, by setting `initialOpenGroupIndex` to `-1`.

feat($theme-default): add initial open group index option

---

packages/@vuepress/theme-default/components/PageEdit.vue

**Summary**
Urls that open files in the web editor follow a slightly different structure on GitLab and GitHub. This is why currently the `editLink`s in VuePress are broken for every GitLab repo.
- GitLab:
```
https://gitlab.com/inkscape/inkscape/-/edit/master/.gitlab-ci.yml
```
- GitHub:
```
https://github.com/vuejs/vuepress/edit/master/README.md
```
The difference is that the repository's name is followed by `/-` in the GitLab links. This PR attempts to fix this issue.
**The PR fulfills these …

fix($theme-default): fix editLink for repos hosted on gitlab.com

---

packages/docs/docs/zh/plugin/README.md
packages/docs/docs/zh/plugin/option-api.md

docs($zh): fix typos

---

packages/docs/docs/zh/guide/deploy.md

docs: update cloudbase deploy doc

---

packages/@vuepress/shared-utils/__tests__/slugify.spec.ts
packages/@vuepress/shared-utils/package.json
packages/@vuepress/shared-utils/src/slugify.ts
yarn.lock

**Summary**
fix #1815
The slugs in the existing URL's will change, so the external links referencing existing pages might break.
So diacritics has some errors in the …

fix($shared-utils): Replace diacritics with String.normalize

---

packages/@vuepress/theme-default/package.json

Use new version to support `@extends` writing
**Summary**
fix #2227

build($theme-default): bump stylus version

---

packages/@vuepress/theme-default/global-components/CodeBlock.vue
packages/@vuepress/theme-default/global-components/CodeGroup.vue
packages/docs/docs/guide/getting-started.md
packages/docs/docs/theme/default-theme-config.md

feat($theme-default): add code group and code block components

---

packages/@vuepress/shared-utils/__tests__/fileToPath.spec.ts
packages/@vuepress/shared-utils/__tests__/parseHeaders.spec.ts
packages/@vuepress/shared-utils/__tests__/unescapeHtml.spec.ts

test: complete existed tests of shared-utils

---

packages/@vuepress/core/lib/client/components/OutboundLink.vue

feat($theme-default): inform screen readers link opens in new tab/window (fix #2601)

---

packages/docs/docs/theme/default-theme-config.md

docs: add in CodeGroup and CodeBlock usage docs

---

packages/@vuepress/core/lib/client/serverEntry.js
packages/@vuepress/core/package.json
yarn.lock

Close #2606 
v3.4.5 fixed a bug with redirections on SSR, I added the `catch` to the initial push since `onReady` should still catch the error
**Summary**

refactor($core): catch initial push to avoid warning

---

packages/docs/docs/miscellaneous/design-concepts.md
packages/docs/package.json

fix: textlint bug causing PR's to fail checks fix #2636

---

packages/@vuepress/theme-default/global-components/CodeGroup.vue

**Summary**
Fixes the `code-group` component by wrapping the buttons in a list for accessibility purpose.
Before on the left
After on the right

fix: adds accessibility to code-group component

---

packages/@vuepress/core/lib/client/components/OutboundLink.vue
packages/@vuepress/theme-default/styles/index.styl
yarn.lock

**Summary**
- [ x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

fix($core): #2627 Dup ID violates HTML5-4

---

packages/@vuepress/core/lib/client/index.ssr.html
packages/@vuepress/core/lib/client/root-mixins/updateMeta.js
packages/@vuepress/core/lib/node/ClientComputedMixin.js
packages/docs/docs/guide/frontmatter.md

**Summary**
This feature introduces the ability to specify `canonical` in the frontmatter section on a page:
```
---
canonical: https://google.com
---
```
Which will …

feat($core): add canonical link to frontmatter

---

packages/@vuepress/plugin-pwa/lib/SWUpdatePopup.vue

**Summary**
Changed z-index from 2 to 3 to avoid conflict with div[class*="language-"]::before elements
**before**
**after**

fix ($plugin-pwa): popup zindex conflict (fix #2642)

---

packages/@vuepress/core/lib/client/components/OutboundLink.vue
packages/@vuepress/theme-default/styles/index.styl

#2627 adds a hint with `sr-only` class, but the class style is placed in `@vue/theme-default` by mistake.
OutboundLink is an internal component, and will effect all the themes, so the style must be placed in the component.

fix($core): add missing styles for `<OutboundLink />`

---

packages/@vuepress/core/lib/node/ClientComputedMixin.js

fix($core): reference correct canonical Url frontmatter property (fix #2665)

---

packages/@vuepress/core/lib/node/createTemp.js

**Summary**
To avoid compilation errors caused by removed files.
Ref: https://github.com/vuejs/vuepress/issues/2254#issuecomment-689457157

fix: Only empty the `.temp` directory at most once per run (fix #2254)

---

packages/@vuepress/markdown/__tests__/link.spec.js
packages/@vuepress/markdown/index.js
packages/@vuepress/markdown/lib/link.js
packages/docs/docs/config/README.md
packages/docs/docs/guide/markdown.md
packages/docs/docs/zh/config/README.md
packages/docs/docs/zh/guide/markdown.md

**Summary**
Extends the markdown link plugin with an option for the page suffix, which is currently hardcoded to `.html`.
This fixes broken links in the markup (and hence non-js version) when using the clean urls plugin. See #2452 for details.
Fixes #2452.
See the [associated feature request issue](https://github.com/vuejs/vuepress/issues/2452) for detailed description and …

feat($markdown): make page suffix configurable (close #2452)

---

packages/@vuepress/theme-default/styles/index.styl

**Summary**
a11y: When using keyboard navigation the header-anchor link (the **#** tag before the heading) is not visible, this PR fixies this bug.
**What kind of change does this PR introduce?**
**Does this PR introduce a breaking change?**
To recreate the issue, try navigating using you keyboard (with the `TAB` key) in a page with many `h1`-`h6` headings. You won't see the heading-anchor link (the **#** tag before the heading). But when you hover with your mouse over a heading you will see the heading-anchor link.
Why? because the code uses only `:hover` (for mouse users). It should also include `:focus` (for keyboard users).

fix($theme-default): display header-anchor links when using keyboard navigation

---

packages/docs/docs/plugin/README.md
packages/docs/docs/zh/plugin/README.md

docs: fix broken link for out-of-box plugin references

---

packages/docs/docs/theme/default-theme-config.md

I think what the documentation wants to say here is
`.vuepress/styles/index.styl`
**Summary**

docs: remove first slash in `./vuepress/styles/index.styl`

---

packages/docs/docs/zh/theme/default-theme-config.md

**Summary**
The old path does not work, use this path to work properly.

docs($zh): update custom page class for default theme config

---

packages/@vuepress/theme-default/components/SidebarLinks.vue

fix: sidebar groups are not opened when directly navigating to these pages (fix #2564)

---

packages/@vuepress/markdown/__tests__/__snapshots__/snippet.spec.js.snap
packages/@vuepress/markdown/__tests__/fragments/Dockerfile
packages/@vuepress/markdown/__tests__/fragments/code-snippet.md
packages/@vuepress/markdown/lib/snippet.js

**Summary**
This PR fixes an issue where [code snippets in markdown](https://v1.vuepress.vuejs.org/guide/markdown.html#import-code-snippets) can reference a filename to include _only if_ the filename has an extension.
For example, including a snippet like this:
```
<<< @/path/to/Dockerfile
```
(note the path does not contain a `.`) results in the snippet being rendered as the string `Invalid code snippet option` even if the target file exists.
The bug is caused by an overly restrictive regex that demands at least one literal `.` in the include path. This PR fixes the regex and adds a test case.
My personal preference would be to refactor the relatively large regex into simpler parsing steps, but I don't want to mess with it and inadvertently introduce subtle side effects :/
**What kind of …

fix($markdown): support path without file extension when importing code snippets

---

packages/@vuepress/core/lib/client/root-mixins/updateMeta.js

fix($core): escape meta tags correctly (fix #2831)

---

packages/docs/docs/guide/getting-started.md

The proposed addition to the Quick Step method builds the generated site - an action that is equivalent to "Step 3. Install VuePress locally" in the [Manual Installation](https://vuepress.vuejs.org/guide/getting-started.html#manual-installation) variant.
**Summary**
To avoid wasting your time, it's best to open a …

docs: improve getting started guide

---

CHANGELOG.md
README.md
packages/docs/docs/guide/README.md
packages/docs/docs/plugin/README.md
packages/docs/docs/plugin/official/plugin-blog.md
packages/docs/docs/theme/blog-theme.md
packages/docs/docs/zh/guide/README.md
packages/docs/docs/zh/plugin/README.md
packages/docs/docs/zh/plugin/official/plugin-blog.md
packages/docs/docs/zh/theme/blog-theme.md

docs: clean all invalid links (close #2955)

---

packages/@vuepress/plugin-last-updated/index.js

**Summary**
The `$page.lastUpdated` generated from _plugin-last-updated_ helds the Date in the localized format. Other plugins like sitemap can hardly work with this …

Add $page.lastUpdatedTstamp

---

packages/docs/docs/guide/deploy.md
packages/docs/docs/zh/guide/deploy.md

docs: add a method to deploy vuepress site with github actions

---

packages/docs/docs/plugin/official/plugin-pwa.md

Fixes issue with docs template code where the favicon was not being served properly in chrome
**Summary**

docs: Add favicon reference in head config template code

---

packages/docs/docs/guide/assets.md

**Summary**
Add `@source` webpack alias to docs. This is can be useful for people who prefer to refer to files from the source folder down instead of a relative folder. 
More background: #2308 …

Docs: Add @source alias

---

packages/@vuepress/core/lib/node/build/index.js
packages/docs/docs/api/cli.md
packages/docs/docs/zh/api/cli.md
packages/vuepress/lib/registerCoreCommands.js

**Summary**
This PR is all about build phase. No need to check browser compability.
To fix #1819. Vuepress build would fail for many docs, for Promise.all push thousands …

feat: add build concurrency control (fix #1819)

---

packages/@vuepress/theme-default/components/Home.vue
packages/docs/docs/index.md
packages/docs/docs/theme/default-theme-config.md
packages/docs/docs/zh/theme/default-theme-config.md

**Summary**
Set `footer` with [Markdown Slot Syntax](../guide/markdown-slot.md) to support rich text:
```md
---
home: true
---
::: slot footer
MIT Licensed | Copyright © 2018-present [Evan You](https://github.com/yyx990803)
:::
```
close: #2993
To avoid wasting your time, it's best to open a **feature request …

feat(theme-default): set home footer with markdown slot (close: #2993)

---

packages/@vuepress/theme-default/components/DropdownLink.vue

**Summary**
Remove non-existing `:blur` pseudo selector from the default theme.
If changing the UI of default theme, please provide the **before/after** screenshot: not applicable
If yes, please describe the impact and migration path for existing applications: not applicable

fix: remove non-existing :blur css pseudo selector

---

packages/@vuepress/types/src/theme-default.ts

fix(types): missing types for `initialOpenGroupIndex` (close: #3129)

---

packages/docs/docs/zh/theme/default-theme-config.md

docs: duplicate text

---

packages/@vuepress/theme-default/styles/index.styl

**Summary**
Currently, when users select the page content to copy & paste the text, it also selects the headings **#** anchors. This PR removes the headings anchor-selection by defining the anchors as not selectable (`user-select: none;`).
To avoid wasting your time, it's best to open a **feature request issue** …

feat(theme-default): headings anchor should not be selectable
