vuejs/vuepress

- docs/guide/README.md
Fix broken link to "Vue-powered custom theme system" on https://vuepress.vuejs.org/guide/
> Fix broken link

- lib/default-theme/NavLinks.vue
This is my biggest pet peeve on earth 😅Love this project so far, can't wait to try it out on something real!
> Capitalize H in GitHub in nav links

- lib/webpack/createClientConfig.js
the issue is here: https://github.com/ben-eb/cssnano/issues/461
> css safe: mergeLonghand = false

- lib/default-theme/NavLinks.vue
Fixed for https://github.com/vuejs/vuepress/issues/125
> Fix unepxected error when themeConfig.nav isn't given.

- lib/default-theme/NavLinks.vue
> fix: Only add language dropdown when there has more than one locale configured.

- lib/default-theme/styles/code.styl
> Tweak highlighted line

- README.md
XD, a tiny contribution.
I'm planning move my blog from Hexo to VuePress❤.
Thank you Vue Team.
Have a nice day.
> docs: Update Multi-Language Support

- docs/guide/deploy.md
Add instructions for deploying to GitLab pages using to GitLab CI
> Add GitLab pages and GitLab CI

- lib/prepare.js
Allows the index.js to be used for plugins and fixes an oversite on the previous pull request.
> fix: renames index.js to enhanceApp.js

- .gitignore
- docs/default-theme-config/README.md
- lib/default-theme/Layout.vue
My first contrib to the Vue community ;)
Picked issue with `contribution welcome` label - #187
> Navbar disabling option (#187)

- docs/guide/deploy.md
I've added two missing < characters in front of REPO>
> Add missing <

- lib/build.js
> fix: dest error set deletes the whole project

- lib/default-theme/NavLink.vue
- lib/default-theme/util.js
Hello,
i've fixed a defect with the href "tel:" in navbars links.
I've seen, he was not in the "externals" links, i've added it.
> fix: tel links in navbar

- lib/prepare.js
> Remove style override limitation to custom theme

- lib/markdown/index.js
- lib/util/index.js
> fix: emoji work with toc (#417)

- lib/webpack/createBaseConfig.js
fix errors:
```bash
Module build failed: ReferenceError: Unknown plugin "transform-vue-jsx" specified in "base" at 0, attempted to resolve relative to ....
```
> fix: resolve absolute module paths

- lib/default-theme/Sidebar.vue
Use v-for with key to fix lint errors.
> chore($sidebar): use v-for with key

- lib/webpack/createBaseConfig.js
add option to 'css-loader'
for display css sourcemap
> fixed createBaseConfig.js for css sourcemap

- docs/guide/deploy.md
> Grammatical / Typo

- lib/default-theme/styles/nprogress.styl
> fix: SyntaxError

- package.json
- yarn.lock
Just update webpack-serve to 1.0.2
test with `yarn dev` and `yarn build` with no error.
> chore(dependency): upgrade webpack-serve

- lib/default-theme/SearchBox.vue
**Summary**
searchbox function go throw a error with no suggestions
> bugfix: searchbox function go throw a error with no suggestions

- lib/default-theme/styles/theme.styl
**Summary**
Thank @klimash
Fix #518
> Fix horizontal scroll on mobile device

- docs/config/README.md
minor addition related to GDPR and Google Analytics
**Summary**
- [x ] Docs
- [x ] No
> Update docs with info about GDPR

- test/jest.config.js
> chore: set rootDir in jest config

- docs/guide/markdown.md
**Summary**
This is just a grammatical change and fixing a letter that should be capitalized.
> fix grammar and capitalize word

- docs/config/README.md
**Summary**
Fix sass-loader link in config document.
https://vuepress.vuejs.org/config/#scss
> fix: sass-loader link in config document.

- lib/dev.js
resolving issue 
https://github.com/vuejs/vuepress/issues/582
**Summary**
> fix [#582] - resolving random HMR port 

- bin/vuepress.js
**Summary**
Close: #598
Close: #570
Release at: **0.11.0**
> feat: set exitCode to non-zero when catching error (close: #598 & #570).

- lib/app/app.js
- lib/default-theme/styles/config.styl
- lib/webpack/createBaseConfig.js
**Summary**
1. duplicated generated override style
2. unexpected style order, override style should be at the end of the extracted style bundle. (ref: https://github.com/webpack-contrib/mini-css-extract-plugin/pull/130) …
> fix: override style issues (close: #637)

- docs/default-theme-config/README.md
> docs (#201): Add note regarding Algolia submission process

- docs/zh/guide/deploy.md
npm run build-docs | yarn build-docs  -> npm run build:docs | yarn build:docs
**Summary**
> fix 中文文档-deploy-netlify-BuildCommand

- scripts/release.sh
**Summary**
When `are you sure? (y/n)`, `[enter]` should enter then by default
> optimize: Update defaults [enter] to passed

- docs/default-theme-config/README.md
**Summary**
Just a missing semi-colon :+1:
> fix: code snippet typo (missing semi-colon)

- lib/default-theme/Navbar.vue
**Summary**
Adds the alt attribute of the site title to the logo image element in the NavBar for improved accessibility.
As this is not really a *feature*, and more of simple improvement and accessibility-fix, I will treat this as a bugfix.
- [ x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
If …
> Add alt attribute to logo

- lib/prepare/index.js
Fix escape characters in windows, such as "\n" (close: #642)
> fix: normalize override file path in windows (#692) (close: #642)

- lib/default-theme/Sidebar.vue
fixes https://github.com/vuejs/vuepress/issues/705
**Summary**
> fix: set alias "collapsible" to "collapsable" (close: #705)

- docs/default-theme-config/README.md
Minor improvements to the service workers section of the theme docs
**Summary**
> Update README: Improve service worker section

- packages/@vuepress/core/lib/internal-plugins/i18nTemp.js
> fix: valid filename for case-sensitive os

- packages/@vuepress/core/lib/internal-plugins/importAsyncComponent.js
- packages/@vuepress/core/lib/plugin-api/option/EnhanceAppFilesOption.js
**Summary**
e.g.
```js
//before
export { default } from 'C:\somedocs\.vuepress\enhanceApp.js'
//after
export { default } from "C:\\somedocs\\.vuepress\\enhanceApp.js" …
```
> fix: escape backslash

- package.json
- packages/docs/package.json
> chore: yarn workspace in script

- docs/guide/markdown.md
> Fix Custom Containers sample output to match input

- lib/app/clientEntry.js
> fix: #818 Missing config.base in google analytics page view URL

- packages/@vuepress/core/lib/dev.js
- packages/@vuepress/plugin-back-to-top/BackToTop.vue
> chore: fix indent and replace back-to-top's v-if by v-show

- lib/default-theme/Home.vue
> chore: Elements in iteration expect to have 'v-bind:key' directives.

- docs/zh/guide/getting-started.md
to avoid ! error: `-bash: !": event not found`
**Summary**
> docs: use echo statement with single quotes

- README.md
**Summary**
Added vuemeetups to websites made with vuepress under community
> added vuemeetups

- packages/@vuepress/cli/package.json
> chore: update peer dependencies

- packages/@vuepress/core/lib/eject.js
> fix: eject failed because config.styl not exist

- packages/@vuepress/plugin-google-analytics/README.md
- packages/@vuepress/plugin-google-analytics/inject.js
**Summary**
this Pull Request is fix for Google Analytics plugin build error and improve README.md file.
> fix: Google Analytics Plugin build error

- packages/@vuepress/theme-default/styles/code.styl
**Summary**
Adds a `php` tag to the top-right corner of PHP code blocks.
**Before**: [![Screenshot from Gyazo](https://gyazo.com/2ae6728cdfad0018817144bfb9e550de/raw)](https://gyazo.com/2ae6728cdfad0018817144bfb9e550de)
**After:** [![Screenshot from Gyazo](https://gyazo.com/c65c0b2b4cdd70cc8f63bf3cd40e005e/raw)](https://gyazo.com/c65c0b2b4cdd70cc8f63bf3cd40e005e)
To avoid wasting your time, …
> Add PHP language text tag to code block.

- packages/docs/docs/guide/deploy.md
> Added now.sh deployment instructions

- packages/docs/docs/guide/directory-structure.md
I think I found a typo
**Summary**
> Change 'emplates' to 'templates'

- packages/@vuepress/plugin-pagination/clientPlugin.js
**Summary**
`Array.prototype.slice` do not include the end index, so the actual posts per page is one less than it should be.
> fix: patch for pagination-plugin posts count

- packages/@vuepress/theme-default/components/SidebarButton.vue
> chore: use pointer for sidebar button

- packages/@vuepress/core/lib/prepare/AppContext.js
**Summary**
`ssr.html` and `dev.html`  were swapped in `AppContext.js`. This fixes that.
> fix($core): correct swapped ssr.html and dev.html

- packages/@vuepress/theme-default/index.js
**Summary**
See title.
_Loving VuePress so far, thanks!_
> Fix Algolia resolution error in theme-default

- docs/default-theme-config/README.md
corrected the docs to account for the split of override.styl into two APIs: override.styl and style.styl
**Summary**
> override.styl to style.styl for custom page class

- lib/prepare/index.js
Updated URL of docs (v0.vuepress.vuejs.org) to fix broken link
**Summary**
This PR fixes a broken link to the docs in the CLI of version 0.x
> Update index.js (fix broken URL)

- packages/docs/docs/guide/markdown.md
**Summary**
The guide does not work as it says. Updating it to something might work.
> fix: doc inconsistency

- packages/docs/docs/plugin/option-api.md
**Summary**
I found this incorrect infomation during developing a plugin
> docs: fix wrong demonstration of add new markdown-it plugin

- packages/@vuepress/plugin-register-components/README.md
**Summary**
This is a tiny fix, there was a minor typo in the readme. I just copied an pasted it from the readme and it took me 20 mins to realise that the code is actually looking for `componentsDir` not `componentDir` …
> Fixes minor typo in the register-components plugin readme

- packages/docs/docs/config/README.md
> Correct spelling

- packages/@vuepress/plugin-blog/index.js
**Summary**
see: https://github.com/vuejs/vuepress/issues/906#issuecomment-439939941
> fix #906 : Blog plugin blocking front matter custom layout config

- packages/@vuepress/core/lib/dev.js
'* + Enter' to log the keys of AppContext, while 'key + Enter' is to log the value of corresponding
field in AppContext
**Summary**
> feat: support debug in dev process

- README.md
- rfcs/README.md
- rfcs/template.md
**Summary**
The "RFC" (request for comments) process is intended to provide a consistent and controlled path for new features to enter VuePress.
> workflow: introducing RFC process.

- packages/@vuepress/plugin-search/SearchBox.vue
**Summary**
Link to issue: https://github.com/vuejs/vuepress/issues/976
Doesn't include a ployfill for Aloglia Search, following …
> fix #976: fix height of input in SearchBox

- packages/docs/docs/theme/default-theme-config.md
**Summary**
It improves the `Home` theme default documentation to describe with a dummy example the following metas:
- `heroText`
- `tagline`
It will simplify the usage of this component without the need to review the component code.
> Extend `Home` example with core properties

- CHANGELOG.md
- packages/@vuepress/core/lib/app/components/Content.js
vuepress version - 1.0.0-alpha.28
When I try to run `yarn docs:build` I get the error:
```
ReferenceError: parent is not defined
at VueComponent.render (node_modules/@vuepress/core/lib/app/components/Content.js:17:6)
at VueComponent.Vue._render (/Users/prefer/src/kernelcare-doc/node_modules/vue/dist/vue.runtime.common.js:4642:22)
at renderComponentInner (/Users/prefer/src/kernelcare-doc/node_modules/vue-server-renderer/build.js:7518:25)
at renderComponent (/Users/prefer/src/kernelcare-doc/node_modules/vue-server-renderer/build.js:7488:5)
at RenderContext.renderNode (/Users/prefer/src/kernelcare-doc/node_modules/vue-server-renderer/build.js:7404:5)
at RenderContext.next (/Users/prefer/src/kernelcare-doc/node_modules/vue-server-renderer/build.js:2469:23)
at cachedWrite …
```
> Variable `parent` is undefined

- packages/@vuepress/core/lib/app/app.js
**Summary**
Re-eneable the scroll to anchor behavior in Vue router.
Fixes #1107
> fix #1107: re-enable scroll to anchor behavior

- packages/@vuepress/core/lib/dev.js
- packages/vuepress/lib/registerCoreCommands.js
**Summary**
Add --open agrument for opening browser when ready. Fix #1100
> feat(core): add --open argument (fix #1100)

- packages/@vuepress/plugin-back-to-top/BackToTop.vue
**Summary**
Use `$accent-color`. Fixes #1121.
> fix(BackToTop): use $accent-color. Fix #1121

- packages/docs/docs/miscellaneous/migration-guide.md
> Fix for Google Analytics instructions

- packages/docs/docs/plugin/context-api.md
> docs: Add missing API reference

- packages/@vuepress/core/lib/app/components/LayoutDistributor.vue
**Summary**
In `LayoutDistributor`, check if the tartget layout component exists or fallback to `Layout`
> chore($core): check if layout exists

- packages/@vuepress/plugin-google-analytics/inject.js
**Summary**
I simply add the anonymize ip setting to true in analytics configuration in order to be compliant with  GDPR.
> set anonymize ip to true

- docs/.vuepress/config.js
- docs/default-theme-config/README.md
**Summary**
I simply fix github edit link when navigate on 0.x documentation. I also document that we can add a logo on default theme navbar.
> Documentation theme logo

- packages/docs/docs/plugin/official/plugin-last-updated.md
> fix: Correct typo

- packages/@vuepress/theme-default/components/Home.vue
**Summary**
Typo closing tag. Comes from #1156
> Solve: Tag <main> has no matching end tag in the Home.vue

- packages/@vuepress/plugin-pwa/lib/i18n.js
**Summary**
i18n. Add Japanese and Spanish language for pwa message.
> chore($pwa): update i18n.js with Spanish and Japanese language

- packages/@vuepress/core/package.json
- yarn.lock
> chore($core): bump vue-router to 3.0.2

- packages/@vuepress/core/lib/prepare/loadTheme.js
> chore($core): resolve theme path to the dir of main file (close #1204)

- packages/docs/docs/guide/deploy.md
> docs(deploy): add documentation about travis

- packages/docs/docs/zh/config/README.md
> extendMarkdown 文档写错了

- packages/@vuepress/markdown/lib/snippet.js
**Summary**
(This is about backend so I think which browser I use does not matter.)
The reason of creating this pr: …
> remove colon as separator, fix #1151

- packages/@vuepress/core/lib/internal-plugins/palette/index.js
- packages/@vuepress/core/lib/internal-plugins/style/index.js
**Summary**
Related to #1170 and #1164 .
#1164 partly fixed this bug for user override, but not for theme override and parent theme override. This PR is to completely fix that.
> fix($core): style and platte path sep on windows (fix #1170)

- packages/@vuepress/theme-default/components/Page.vue
> fix: bitbucket edit link goes to wrong link (#1235)

- packages/docs/docs/zh/guide/markdown.md
> fix: lineNumbers example should add space to make IDE happy

- lib/default-theme/Page.vue
**Summary**
- [X ] Bugfix
- [X ] No
This backports the fix from vuejs#1235 to 0.x
> Add fix from vuejs#1235 to fix bitbucket links.

- packages/docs/docs/guide/markdown.md
> Edit wording

- README.md
> Add instructions for npm install

- packages/docs/docs/plugin/option-api.md
- packages/docs/docs/zh/plugin/option-api.md
> fix document

- packages/docs/docs/guide/markdown.md
> Added information on syntax highlighting

- lib/markdown/snippet.js
**Summary**
(This is about backend so I think which browser I use does not matter.)
This is the 0.x branch version of #1236 .
> [0.x] remove colon as separator, fix #1297

- packages/@vuepress/markdown/lib/highlight.js
**Summary**
Adding support for Ruby syntax highlighting using https://vuepress.vuejs.org/guide/markdown.html#import-code-snippets
> add ruby support for syntax highlighting

- packages/@vuepress/core/lib/app/redirect.js
> fix($core): redirecting based on lower case (close: #1317)

- packages/docs/docs/zh/plugin/official/plugin-active-header-links.md
> fix a typo

- packages/@vuepress/theme-default/components/Page.vue
> fix a typo in Page.vue

- packages/docs/docs/config/README.md
- packages/docs/docs/faq/README.md
- packages/docs/docs/guide/assets.md
- packages/docs/docs/guide/basic-config.md
- packages/docs/docs/guide/deploy.md
- packages/docs/docs/guide/getting-started.md
- packages/docs/docs/guide/global-computed.md
- packages/docs/docs/guide/markdown-slot.md
- packages/docs/docs/guide/using-vue.md
- packages/docs/docs/theme/using-a-theme.md
- packages/docs/docs/theme/writing-a-theme.md
> fix serveral punctuation and grammar problems

- packages/docs/docs/guide/using-vue.md
- packages/docs/docs/zh/guide/using-vue.md
> add a reminder for the Badge component specific to the default theme

- packages/docs/docs/config/README.md
- packages/docs/docs/zh/config/README.md
**Summary**
Add more informations on `dest`.
> docs: add more informations on `dest`

- packages/@vuepress/markdown/lib/snippet.js
**Summary**
Support code snippet HMR.
It will solve #1309 and is based on #1337.
A relavent PR (#1316) is closed and will be splitted to several parts.
> feat($markdown): code snippet hmr (close #1309)

- packages/docs/docs/guide/markdown.md
> docs: fix image preview

- lib/default-theme/styles/theme.styl
**Summary**
This reverts commit [b7f3ac4](https://github.com/vuejs/vuepress/commit/b7f3ac48dcf6866c2b552be8ad1e1c45a729a1f0)
fix #1355
> fix: missing sidebar button on a mobile homepage (close: #1355)

- .github/ISSUE_TEMPLATE/bug_report.md
**Summary**
Fix an incorrect article in bug_report.md
> fix an incorrect article in bug_report.md

- packages/docs/docs/zh/plugin/official/plugin-active-header-links.md
> docs: fix a 404 link

- packages/@vuepress/core/lib/plugin-api/index.js
> fix($core): skip plugin on error (close: #1371)

- packages/@vuepress/markdown/lib/highlightLines.js
> fix($markdown): fix line highlighting (close: #1364)

- packages/docs/docs/guide/deploy.md
- packages/docs/docs/zh/guide/deploy.md
**Summary**
Set node.js lts version in `.travis.yml`.
```yml
node_js:
- lts/*
```
Without it, travis-ci will use nodejs `v0.10.48` to build it.
You can see [Travis …
> docs: Github Pages and Travis CI

- packages/@vuepress/plugin-blog/index.js
> fix: fix blog plugin path bug

- packages/@vuepress/plugin-register-components/index.js
- packages/docs/docs/plugin/official/plugin-register-components.md
- packages/docs/docs/zh/plugin/official/plugin-register-components.md
> feat($plugin-register-components): custom name registration (close: #656)

- packages/@vuepress/markdown/lib/highlight.js
[xxx.styl] file use stylus code style
**Summary**
- [x ] Bugfix
- [ x] No
- [x ] Chrome
- [x ] Safari
> fix(markdown-highlight): PrismJs can't read styl style

- docs/guide/markdown.md
**Summary**
Fixes a small typo.
> docs: fix a typo

- lib/default-theme/SidebarButton.vue
> fix: cursor pointer

- lib/default-theme/Home.vue
**Summary**
- [ x] Bugfix
- [x ] No
- [x ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x ] Chrome
**Other …
> fix #849 hero image resizing

- packages/@vuepress/core/lib/node/build/index.js
> feat($core): decode page path for better readablility

- packages/@vuepress/plugin-pwa/lib/SWUpdatePopup.vue
> Fix typo in `opacity`

- packages/@vuepress/core/lib/client/components/Content.js
- packages/@vuepress/markdown/lib/highlight.js
> chore: lint fix

- packages/@vuepress/markdown-loader/index.js
**Summary**
Always use `/` instead of `\` in relPath.
**Bad:**
https://github.com/vuejs/vuepress/blob/7848a309f732123f318c86865e4e2616069b8132/packages/%40vuepress/markdown-loader/index.js#L68
**Good:**
https://github.com/vuejs/vuepress/blob/7848a309f732123f318c86865e4e2616069b8132/packages/%40vuepress/core/lib/node/Page.js#L68
If adding a **new feature**, the PR's …
> fix($markdown-loader): always use `/` instead of `\` in `relPath`

- packages/@vuepress/core/lib/index.js
**Summary**
```js
const { version } = require('vuepress')
```
> feat($core): add version

- .github/ISSUE_TEMPLATE/feature_request.md
**Summary**
Remove unnecessary markdown formatting in the GitHub feature request template.
GitHub template, does not affect any code of vuepress.
> Fix GitHub template

- packages/@vuepress/core/lib/node/plugin-api/util.js
**Summary**
Sometimes we want our plugins to have array as options:
```js
module.exports = (options) => {
options.forEach((item) => {
// do something
})
}
```
N/A
> feat($core): support array as plugin options

- packages/@vuepress/theme-default/index.js
**Summary**
ref: https://v1.vuepress.vuejs.org/theme/default-theme-config.html#active-header-links
#1488
> $theme-default: support options.activeHeaderLinks (close: #1488)

- packages/docs/docs/plugin/README.md
**Summary**
Improve the English version for a line in the documentation.
> fix: improve English in the docs

- docs/guide/assets.md
> add information about absolute paths for .vuepress/public dir

- lib/webpack/createServerConfig.js
> fix #451: fix webpack externals

- packages/@vuepress/core/lib/node/Page.js
> fix #1443: Use directory name to compute slug if filename is readme or index

- docs/config/README.md
**Summary**
While this document is solely concerned with documenting the configuration options, it isn't very explicit regarding structure or the addition of …
> Add CSS preprocessor tip to Build Pipeline section

- packages/docs/docs/config/README.md
**Summary**
As previously in 0.x, information on installing CSS pre-processors was dissociated with the config documentation. This provides a link directly to that …
> Add tip to explain CSS pre-processor installation

- packages/@vuepress/markdown/__tests__/__snapshots__/snippet.spec.js.snap
- packages/@vuepress/markdown/__tests__/snippet.spec.js
**Summary**
When the yarn test command is run, the test for the snippet in the result is misspelled.
N/A
> fix($test):fix spelling error of the word snippet,it used to be snipets

- packages/@vuepress/core/lib/node/Page.js
- packages/@vuepress/core/lib/node/util/index.js
> Using directory name to get page date if it is not specified elsewhere

- packages/@vuepress/theme-default/README.md
**Summary**
Updated README.md in default-theme to indicate the usage of plugin-search
> Indicate that plugin-search is used.

- docs/config/README.md
> Correct the link in the docs for 0.x slugify default source

- packages/docs/docs/api/cli.md
- packages/vuepress/lib/registerCoreCommands.js
- packages/vuepress/package.json
Shows up useful information regarding the local environment:-
```bash
Environment Info:
System:
OS: Linux 4.18 Ubuntu 18.10 (Cosmic Cuttlefish)
CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
Binaries:
Node: 8.11.4 - /usr/bin/node
Yarn: Not Found
npm: 6.9.0 - /usr/local/bin/npm
Browsers:
Chrome: 74.0.3729.108
Firefox: 63.0
npmGlobalPackages:
@vuepress: v.0.14.11
```
**Summary**
> feat($core): New info command

- packages/docs/docs/theme/writing-a-theme.md
**Summary**
Fix a small typo in the plugin syntax
> docs: Fix incorrect plugin syntax in themes

- docs/guide/basic-config.md
It wasn't needed anyway.
**Summary**
> Removed sentence-ending preposition.

- packages/docs/docs/config/README.md
- packages/docs/docs/zh/config/README.md
update the EN doc
**Summary**
- [ x] Docs
- [x ] No
- [x ] Chrome
> doc: add 'extraWatchFiles' option to the documentation

- docs/guide/markdown.md
**Summary**
Clarify where to put frontmatter for users not used to it
> Clarify where to put frontmatter if not used to it

- packages/docs/docs/zh/guide/README.md
> docs(guide): fix link anchor typo

- packages/docs/docs/guide/global-computed.md
> Use English in example of global-computed.md

- packages/@vuepress/theme-default/layouts/404.vue
**Summary**
$theme-default: using class '.theme-default-content' instead of '.content' in 404 layout
- **before**
- **after**
>  $theme-default: using '.theme-default-content' to replace '.content'  in 404 layout

- packages/@vuepress/plugin-pwa/package.json
**Summary**
Fixed annoying deprecation warnings of the outdated `joi` dependencies.
Though it's a major version bump, there seem to be no user-facing breaking changes for vuepress.
**Other …
> chore: update workbox-build to v4

- packages/docs/docs/guide/README.md
> Fix typo on blog theme documentation link

- packages/docs/docs/guide/global-computed.md
> Fixed old example of 0.x docs

- packages/docs/docs/guide/permalinks.md
> Fixed minor grammar

- packages/@vuepress/theme-default/util/index.js
**Summary**
Allow users to have links that open system applications (i.e. deep links).
My company is using Vuepress for an internal documentation site. We would like to …
> Default Theme - External Link Regex: Allow for System Deep Links

- packages/docs/docs/theme/option-api.md
> Just fixed a small typo

- packages/docs/docs/api/cli.md
> docs: fix typo

- packages/@vuepress/theme-default/layouts/Layout.vue
- packages/@vuepress/theme-default/styles/code.styl
**Summary**
Import Prism theme in stylesheets instead of SFCs ([`layout.vue`](https://github.com/vuejs/vuepress/blob/834010e650158831675107f5f529ce0b997b7453/packages/%40vuepress/theme-default/layouts/Layout.vue#L149)) to allow custom styles to override them.
Related: #736 #1401 
To avoid wasting your time, it's …
> refactor(theme-default): import prism theme in stylesheets

- packages/@vuepress/theme-default/components/AlgoliaSearchBox.vue
**Summary**
Use `router.push` for Algolia search suggestion links to provide a better experience (no refresh).
> feat(theme-default): use router for Algolia search

- docs/guide/basic-config.md
**Summary**
Minor update to documentation text.
When setting up for the first time, I used the example `config.js` and expected to see the `description` text from the example somewhere in the app. When it wasn't there I thought I had done something wrong and spent time backtracking, double-checking, thinking VuePress was broken, etc. By adding the wording from this page, https://vuepress.vuejs.org/config/#description, I think it is more clear to newcomers where to expect to find the text they have configured and how they can know their config is working.
- [x ] No
If yes, please …
> Clarify example text

- packages/docs/docs/plugin/official/plugin-google-analytics.md
Changed wording to accomodate already anaonymized IPs
**Summary**
No need to mention setting up anonymized IPs as it happens regardless as mentioned [here](https://github.com/vuejs/vuepress/blob/master/packages/%40vuepress/plugin-google-analytics/enhanceAppFile.js#L20). This PR fixes #1687
**The PR fulfills these requirements:**x
To avoid wasting your …
> Updated GA Documentation fix #1687

- README.md
- package.json
- packages/vuepress/package.json
Hi, I'm making updates for Open Collective. Either you or another core contributor signed this repository up for Open Collective. This pull request adds financial contributors from your Open Collective https://opencollective.com/vuepress ❤️
What it does:
- adds a badge to show the latest number of financial contributors
- adds a banner displaying contributors to the project on GitHub
- adds a banner displaying all individuals contributing financially on Open Collective
- adds a section displaying all organizations contributing financially on Open Collective, with their logo and a link to their website
We have also added a `postinstall` script to let people know after `npm|yarn install` that you are welcoming donations. Feel free to remove it if you don't want it. [[More …
> Activating Open Collective

- packages/@vuepress/core/lib/node/webpack/createBaseConfig.js
**Summary**
My use case only needs that the generated js code is transpiled to es5 to make my components compatible with ie. Feel free to close this PR and open a better …
> fix($core): transpile all core js (#1623)

- package.json
> fix: fix script typo

- README.md
> chore: remove next badge from readme

- README.md
**Summary**
Improve README contribution section
> Improve README contribution section

- package.json
**Summary**
Remove duplicate dependencies in `package.json`
Remove useless infos in `package.json`
> Remove duplicate dependencies in package.json

- packages/@vuepress/theme-default/components/AlgoliaSearchBox.vue
**Summary**
Add missing hash in #1706.
> fix: add missing hash in #1706

- .github/semantic.yml
**Summary**
This also awaits the validation of the [Semantic PR Probot](https://github.com/probot/semantic-pull-requests).
> chore: add Semantic Pull Requests configuration

- packages/docs/docs/zh/config/README.md
fix: palette.styl link
**Summary**
- [X ] Bugfix
- [ X] No
- [ X] Chrome
> doc: fix palette.styl link error

- .github/CONTRIBUTING.md
> workflow: add CONTRIBUTING.md

- CHANGELOG.md
> Extra line break removed

- README.md
**Summary**
Made the license badge point to the respective file.
N/A
> docs: Update badge license link

- .all-contributorsrc
- README.md
> chore(member): add `vinayakkulkarni` as a core contributor

- packages/docs/docs/.vuepress/config.js
> feat: reenable search

- packages/docs/docs/zh/miscellaneous/design-concepts.md
> #1812 - Broken link in chinese doc

- packages/@vuepress/core/package.json
- yarn.lock
**Summary**
It's pretty trivial and the tests pass.
> fix:  #1845 bump js-yaml

- .github/semantic.yml
> fix($semantic-config): Check title only for PRs

- packages/@vuepress/theme-default/components/PageEdit.vue
**Summary**
This PR closes #1762
> fix($theme-default): Fix editLink on specific page

- packages/@vuepress/markdown/lib/highlight.js
> fix($markdown): Highlight kotlin code on snippets import

- CHANGELOG.md
**Summary**
We don't need these `fixes` of `feat` commits which are irrelevant to actual code to appear in changelog, such as CI, documents, etc. because these do not take any effects to user's code.
IMO, these informations plus real changelog can be archived into a unified section, such as "release note"? This is worth discussing.
If adding a **new feature**, the PR's …
> workflow: simplify changelog

- packages/@vuepress/core/lib/client/plugins/Store.d.ts
> fix($core): typo in types defs

- README.md
> docs: normalize name of vuepress

- packages/docs/docs/plugin/official/plugin-pwa.md
- packages/docs/docs/zh/plugin/official/plugin-pwa.md
**Summary**
In doc the example of a fully PWA-compliant configuration with VuePress has the wrong format
> fix($docs): PWA-compliant configuration example object

- packages/docs/docs/plugin/README.md
> fix($docs): a _little_ typo in plugin README

- packages/docs/docs/theme/option-api.md
**Summary**
Fixed GlobalLayout reference url in docs.
> fix($docs): Update GlobalLayout reference url in docs

- README.md
Removing myself from the Core Team...so sorry I can't seem to find the time to contribute properly. My best wishes!
**Summary**
> rearrange Core Team

- yarn.lock
…for your changes. Lines starting
**Summary**
> feat($dependencies): Update yarn.lock

- packages/@vuepress/core/lib/node/App.js
- packages/@vuepress/core/lib/node/__tests__/prepare/fixtures/docs-patterns/.vuepress/config.js
- packages/@vuepress/core/lib/node/__tests__/prepare/fixtures/docs-patterns/README.md
- packages/docs/docs/config/README.md
- packages/docs/docs/zh/config/README.md
**Summary**
- [x ] Feature
- [x ] No
Right now the pattern configuration of what files should be resolved as pages is hardcoded in core module of vuepress (APP.js line 319). The intention it's to open the door to parametrizing this pattern configuration from the siteConfig.
fix #1700 
- [ x] Chrome
- [ x] Firefox
- [x ] Safari
- [ x] A convincing reason for adding this feature
- [ x] Related documents have been updated
- [ x] Related tests have been updated
> feat($core): config pattern of resolved files

- README.md
> fix($docs): Broken link "Contribute" on README.md (fix #1953)

- packages/@vuepress/markdown/lib/preWrapper.js
> chore($markdown): Fix typo in packages/@vuepress/markdown/lib/preWrapper.js

- packages/@vuepress/theme-default/layouts/Layout.vue
- packages/@vuepress/theme-vue/layouts/Layout.vue
> fix($theme-default): slots don't allow customization for Sidebar & Page (close: #1950)

- packages/docs/docs/theme/default-theme-config.md
**Summary**
Add the Navbar logo section in the docs, from v0 docs to v1 docs.
it's a fix for #1932
- [x ] No
> feat($docs): Add Navbar Logo section for Default Theme Config (Closes #1932)

- docs/zh/default-theme-config/README.md
**Summary**
Reference to #1974, but for 0.x.
> docs($cn): add Navbar Logo section for Default Theme Config

- packages/@vuepress/core/lib/node/plugin-api/index.js
It should be "encountered" not "encounted".
**Summary**
- [ X] Other, please describe: english typo in error message
- [ X] No
> Fix english typo in error message

- packages/docs/docs/miscellaneous/design-concepts.md
**Summary**
**What kind of change does this PR introduce?**
**Does this PR introduce a breaking change?**
> docs: Fix design concepts typo

- README.md
- packages/@vuepress/markdown-loader/README.md
- packages/@vuepress/markdown/README.md
- packages/@vuepress/plugin-active-header-links/README.md
- packages/@vuepress/plugin-back-to-top/README.md
- packages/@vuepress/plugin-google-analytics/README.md
- packages/@vuepress/plugin-last-updated/README.md
- packages/@vuepress/plugin-medium-zoom/README.md
- packages/@vuepress/plugin-nprogress/README.md
- packages/@vuepress/plugin-pwa/README.md
- packages/@vuepress/plugin-register-components/README.md
- packages/@vuepress/plugin-search/README.md
- packages/@vuepress/shared-utils/README.md
- packages/@vuepress/test-utils/README.md
- packages/@vuepress/theme-default/README.md
- packages/@vuepress/theme-vue/README.md
- packages/docs/docs/plugin/official/plugin-last-updated.md
- packages/docs/docs/plugin/official/plugin-register-components.md
- packages/docs/docs/zh/plugin/official/plugin-register-components.md
- packages/vuepress/README.md
> fix($docs): Uniforming VuePress labels (fixes #1998)

- packages/docs/docs/.vuepress/nav/zh.js
**Summary**
Adding zh nav-link for local development（本地开发）.
> docs($cn): fix and translate nav-link for local development

- packages/docs/docs/.vuepress/config.js
- packages/docs/docs/zh/faq/README.md
**Summary**
Add plugin flowchart to `docs/.vuepress/config.js`, and fix a small bug in zh docs.
affected pages:
- [design-concepts](https://v1.vuepress.vuejs.org/miscellaneous/design-concepts.html#loading-priority)(and [zh](https://v1.vuepress.vuejs.org/zh/miscellaneous/design-concepts.html#%E5%8A%A0%E8%BD%BD%E4%BC%98%E5%85%88%E7%BA%A7))
- [FAQ](https://v1.vuepress.vuejs.org/faq/#why-can-t-palette-styl-and-index-styl-merge-into-one-api)(and [zh](https://v1.vuepress.vuejs.org/zh/faq/#%E4%B8%BA%E4%BB%80%E4%B9%88%E4%B8%8D%E8%83%BD%E6%8A%8A-palette-styl-%E5%92%8C-index-styl-%E5%90%88%E5%B9%B6%E5%88%B0%E4%B8%80%E4%B8%AA-api))
**Does this PR …
> docs: apply plugin flowchart and fix a small bug

- packages/docs/docs/zh/guide/directory-structure.md
> fix invalid link for default template files

- packages/docs/docs/guide/deploy.md
**Summary**
This commit updates the sample Travis CI config used in the docs to deploy VuePress. Travis CI includes a config linter online and I made these changes from the feedback from the Travis CI config linter. These changes work cleanly with the latest API version of Travis CI at time of commit.
> docs: Change Travis CI config to match API changes

- packages/docs/docs/plugin/official/plugin-pwa.md
- packages/docs/docs/zh/plugin/official/plugin-pwa.md
v-slot can only be used on components
added v-if
> fix(PWA): fixed example for the custom component

- packages/@vuepress/theme-default/components/PageNav.vue
- packages/docs/docs/guide/frontmatter.md
- packages/docs/docs/zh/guide/frontmatter.md
> feat($theme-default): external links in prev/next (close #1962)

- packages/docs/docs/guide/deploy.md
- packages/docs/docs/plugin/official/plugin-google-analytics.md
- packages/docs/docs/zh/guide/deploy.md
- packages/docs/docs/zh/plugin/official/plugin-google-analytics.md
**Summary**
Ref: #1936 #1286 
If you think this is a good idea, I will finish the corresponding Chinese document.
> docs: Put yarn in front of npm

- packages/docs/docs/plugin/README.md
> fix: Typo in documentation

- packages/docs/docs/faq/README.md
- packages/docs/docs/zh/faq/README.md
**Summary**
Head [FAQ](https://vuepress.vuejs.org/faq/#when-do-i-need-to-use-enhanceappfiles), you'll find example links are broken.
@vuepress/plugin-pagination is deprecated
@vuepress/plugin-blog are now available under [VuePress](https://github.com/vuepressjs)
I add @vuepress/plugin-google-analytics as an alternative and fix plugin blog's link.
If adding a **new …
> docs: update plugins FAQ example links

- packages/docs/docs/guide/i18n.md
- packages/docs/docs/zh/guide/i18n.md
**Summary**
docs: add missing comma in i18n.md
> docs: add missing comma in i18n.md

- packages/vuepress/cli.js
- packages/vuepress/package.json
**Summary**
Notify users of an newer release so that they don't end up in an outdated version. 
Closes #2119 
> feat($cli): Notify users of a newer release

- packages/docs/docs/plugin/official/plugin-pwa.md
**Summary**
Fix plugin pwa docs example
> docs: Update plugin pwa docs

- packages/@vuepress/core/lib/client/index.ssr.html
- packages/@vuepress/core/lib/node/build/index.js
**Summary**
Add a generator meta tag to ssr index.html template.
Fix #1992 
> feat($core): Add generator meta tag to ssr index.html template

- README.md
> docs: Add vuepress.tools to the readme showcase section

- packages/vuepress/lib/util.js
> fix($cli): update known command list

- packages/@vuepress/core/lib/node/webpack/createBaseConfig.js
**Summary**
Close #2058 
JSX will be disabled if `evergreen` is set to `false`. It's TBD if we should support JSX by default.
> fix($core): resolve jsx files by default (close #2058)

- packages/vuepress/package.json
- yarn.lock
> build: bump cac from 6.5.5 to 6.5.6

- packages/@vuepress/core/package.json
- yarn.lock
**Summary**
This PR update babel version, and bump to core-js@3, as core-js@2 is deprecated.
> build($core): bump babel and core-js version (close #2046)

- packages/@vuepress/theme-default/util/index.js
> fix($theme-default): highlight Chinese title after refresh (close #2078)

- .all-contributorsrc
- README.md
> docs: remove filip from core team for now

- packages/@vuepress/plugin-pwa/index.js
- packages/@vuepress/plugin-pwa/lib/enhanceAppFile.js
> fix($plugin-pwa): popup component does not work (close #2172)

- packages/docs/docs/guide/deploy.md
- packages/docs/docs/zh/guide/deploy.md
- add new link to ZEIT Now example of a VuePress site deployment
- change 'Now' to 'ZEIT Now' as this the correct name
**Summary**
> docs: fix broken link to deploy with ZEIT Now

- packages/@vuepress/shared-utils/src/slugify.ts
**Summary**
- [*] Other, please describe:
enhancement, added to the range of characters handled by markdown.slugify
- [*] No
> fix($shared-utils): Slugify em/en dash in urls

- packages/@vuepress/core/lib/node/build/index.js
> fix($core): missing 404 page (close #2248)

- packages/docs/docs/theme/inheritance.md
- packages/docs/docs/zh/theme/inheritance.md
**Summary**
Minor typo fixed in the docs to avoid confusion. The module imported is `Navbar` not `Home`.
> docs: Fix a minor typo in an import example

- packages/docs/docs/zh/config/README.md
> docs($zh): add a reference link to styling config

- packages/docs/docs/theme/blog-theme.md
**Summary**
Just spotted a minor typo:
> Please _**h**ead_ documentation to see the available options.
Proposed change:
> Please _**r**ead_ documentation to see the …
> docs: fix a minor typo in blog-theme.md

- packages/docs/docs/zh/guide/deploy.md
> docs($zh): add 21yunbox for deployment

- packages/docs/docs/theme/default-theme-config.md
> docs: add more details of path options in sidebar group

- .commitlintrc.js
**Summary**
Allow using `$cn` scope. It might be helpful when dealing with missing part in Chinese docs. 
Check out commit history, you will see that we've used it before. 
**Other …
> build: allow $zh scope in commitlint

- packages/docs/docs/guide/directory-structure.md
> docs: fix grammar in directory-structure.md

- packages/@vuepress/core/lib/node/internal-plugins/style/client.js
**Summary**
VuePress will create an empty chunk every time.
repro: https://github.com/Shigma/vuepress-generates-empty-chunk
> fix($core): no dynamic import style

- packages/docs/docs/guide/deploy.md
Ref: https://vercel.com/blog/zeit-is-now-vercel
**Summary**
> docs: rename ZEIT to Vercel

- packages/@vuepress/core/lib/node/theme-api/index.js
- packages/@vuepress/test-utils/lib/createJestRunner.js
- packages/vuepress/lib/util.js
> chore: fix typos in comment

- packages/@vuepress/shared-utils/README.md
> chore($shared-utils): fix typo

- packages/@vuepress/core/lib/client/root-mixins/updateMeta.js
> perf($core): fix typos

- packages/docs/docs/guide/markdown.md
**Summary**
- [x ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
> docs: refine Markdown Extensions Custom Containers(fix #2141)

- packages/@vuepress/shared-utils/src/inferTitle.ts
> fix($shared-utils): use title variable for homepage (fix #2247)

- packages/@vuepress/core/lib/node/dev/index.js
**Summary**
Fix the watch files
> fix: watch for chokidar v3

- README.md
Removing broken link
**Summary**
> docs: Removed broken gallery link

- packages/@vuepress/theme-default/util/index.js
- packages/docs/docs/theme/default-theme-config.md
**Summary**
This PR allows you to define `'auto'` in defined sidebars, to allow you do define groups of pages that should have sidebars automatically generated. This fixes #1252, which has some detailed use cases + rationale from others.
The change only adds an additional case to check specifically for an `'auto'` configuration so it shouldn't be breaking
For example:
```js
// .vuepress/config.js
themeConfig: {
sidebar: {
'/handbook/project-management/': [
'scope',
'sprints',
'repositories',
],
'/handbook/tools/': [
'slack',
'github',
'deployment',
],
'/': 'auto',
},
}
```
**Does this PR introduce a breaking change?** …
> feat($default-theme): allow 'auto' in defined sidebar (fix #1252)

- packages/docs/docs/miscellaneous/glossary.md
> docs: Correct typo parentThemePath -> parentThemeEntry

- packages/docs/docs/README.md
- packages/docs/docs/guide/getting-started.md
> docs: Make scaffolding path a first-class citizen

- README.md
**Summary**
The old URL of vuepress.tools is no longer available.
> docs: update vuepress.tools link

- packages/@vuepress/theme-default/components/DropdownLink.vue
**Summary**
| Before | After |
|-------------|-------------|
| ![image](https://user-images.githubusercontent.com/120486/86613816-c3eaf900-bfba-11ea-8447-2fc74bc73bd7.png) | ![image](https://user-images.githubusercontent.com/120486/86613840-ca797080-bfba-11ea-9e4a-01ff953d06f8.png) |
To avoid wasting your time, …
> style: change dropdown item heading padding (fix #2481)

- packages/docs/docs/guide/deploy.md
**Summary**
Adding vuepress command for Netlify build command
> docs: Adding vuepress command in Netlify build command

- packages/@vuepress/core/lib/node/webpack/createBaseConfig.js
**Summary**
In the main project package.json If sideeffects is false, it will result in the loss of CSS after vuepress is packaged, issue is [here](https://github.com/vuejs/vuepress/issues/2350), and repo is [here](https://github.com/nashaofu/grender) and [here](https://github.com/nashaofu/vuepress-bug)
To avoid …
> fix($core):  Loss of CSS after build (fix #2350)

- packages/docs/docs/guide/assets.md
- packages/docs/docs/guide/directory-structure.md
- packages/docs/docs/guide/frontmatter.md
- packages/docs/docs/guide/global-computed.md
- packages/docs/docs/guide/markdown.md
- packages/docs/docs/guide/permalinks.md
> docs: fix doc issues

- packages/docs/docs/guide/markdown.md
Small fix in the markdown
**Summary**
> Documentation fix emojis link

- packages/docs/docs/zh/guide/deploy.md
**Summary**
Add CloudBase deploy doc
> docs: add cloudbase deploy doc

- packages/docs/docs/.vuepress/nav/en.js
> docs: reduce priority of 0.x docs

- packages/docs/docs/theme/default-theme-config.md
- packages/docs/docs/theme/inheritance.md
- packages/docs/docs/theme/option-api.md
- packages/docs/docs/theme/using-a-theme.md
- packages/docs/docs/theme/writing-a-theme.md
- packages/docs/docs/zh/theme/default-theme-config.md
- packages/docs/docs/zh/theme/inheritance.md
- packages/docs/docs/zh/theme/option-api.md
- packages/docs/docs/zh/theme/using-a-theme.md
- packages/docs/docs/zh/theme/writing-a-theme.md
Fixes: #2533
**Summary**
Clarify what files config file examples refer to.
I'm not sure if `.vuepress/theme/index.js` or `themePath/index.js` is more appropriate & …
> docs: clarify theme config files in code blocks (close #2533)

- packages/docs/docs/theme/default-theme-config.md
Figuring this out was the first pain point for me in getting started with VuePress. So I think maybe above bar to add a line like this.
**Summary**
> docs: add clarification on theme ejection

- packages/docs/docs/guide/deploy.md
Here is my issue: https://github.com/vuejs/vuepress/issues/2584
I've found that node:9.11.1 is too old and in the `Prerequisites` part of the guide, it's recommend to use node 10+ so update a small comment could be useful. I don't know if it is applicable to delete `node:9.11.1` and replace with `node:14.8.0` so I just add a comment
**Summary**
If adding a **new feature**, …
> docs: update node version for gitlab ci config

- packages/@vuepress/core/lib/client/app.js
> fix: scroll hash encoded when non-english chars are used fix #2633

- packages/@vuepress/plugin-back-to-top/package.json
**Summary**
It's a simple fix of 404 URL in package.json of `back-to-top` plugin.
> docs: fix back-to-top plugin package.json homepage URL 404

- packages/docs/docs/guide/frontmatter.md
**Summary**
Update canonicalUrl frontmatter version to reflect typo fix
> docs: change canonicalUrl frontmatter version

- packages/docs/docs/guide/global-computed.md
- packages/docs/docs/guide/using-vue.md
> docs: link between global-computed and using-vue

- packages/@vuepress/plugin-google-analytics/enhanceAppFile.js
**Summary**
Base path was missing from Analytics report.
Closes #2169
> fix($plugin-google-analytics): report site base (#2687) (close #2169)

- packages/@vuepress/theme-default/global-components/CodeBlock.vue
- packages/@vuepress/theme-default/global-components/CodeGroup.vue
**Summary**
Fixing an issue where the code group doesn't render on initial load
> fix($core): component CodeGroup loads correctly on clientfix #2711

- packages/@vuepress/core/lib/client/redirect.js
**Summary**
- return `true` if a `route` match instead of filter all and check length
- store `path.toLowerCase()` to `pathLower` (don't call each route)
> refactor($core): use `some` instead of `filter` when checking route existence

- packages/docs/docs/zh/plugin/official/plugin-register-components.md
> docs($zh): translate register plugin description

- packages/docs/docs/theme/default-theme-config.md
- packages/docs/docs/zh/theme/default-theme-config.md
**Summary**
Follow up of https://github.com/vuepress/vuepress-next/pull/542
This PR adds a mention to the Algolia `appId` with a small description in the config snippet …
> docs: mention Algolia `appId` option in config snippet

- packages/docs/docs/guide/frontmatter.md
> Front matter language example should use `lang`

- packages/docs/docs/zh/guide/using-vue.md
Delete the redundant blank space to formatting the title.
**Summary**
> docs: update using-vue.md

- packages/docs/docs/guide/markdown.md
> docs: Fixed Spelling Error

- packages/docs/docs/zh/guide/markdown.md
> docs(markdown): update Page Suffix translation

- packages/@vuepress/theme-default/index.js
**Summary**
[The relevant section is here.](https://vuepress.vuejs.org/guide/markdown.html#custom-containers)
**before**
**after**
> docs: fix display after markdown conversion

- packages/docs/docs/guide/markdown.md
- packages/docs/docs/zh/guide/markdown.md
**Summary**
Fixes broken links to the container plugin.
n/a - Only fixes markdown links.
> docs: broken links to plugin-container

- packages/docs/docs/guide/deploy.md
> Guide: Deploy VuePress to Layer0

- tsconfig.json
**Summary**
close: #2981, tsc assets compatibility issue introduced at https://github.com/vuejs/vuepress/commit/daa6404bf7b46331d0751af58a2c8a6c5c7cc3f9#diff-b55cdbef4907b7045f32cc5360d48d262cca5f94062e353089f189f4460039e0
- https://unpkg.com/browse/@vuepress/shared-utils@1.8.3/lib/env.js
- https://unpkg.com/browse/@vuepress/shared-utils@1.9.0/lib/env.js
If adding a **new …
> fix(core): compatibility with node 10 (close: #2981)

- packages/docs/docs/guide/deploy.md
- packages/docs/docs/zh/guide/deploy.md
**Summary**
Fix incorrect script in deploy.md : 
According to documentation and comparison with other part, I changed script in [this section](https://github.com/vuejs/vuepress/blob/master/packages/docs/docs/guide/deploy.md#github-pages-and-github-actions:~:text=BUILD_SCRIPT%3A%20yarn%20%26%26%20yarn%20build)
And it works well on my [project pages](https://torchei.github.io/TorchEI/)
You have tested in the following browsers: (Providing a detailed version will …
> docs:  fix deploy.md

- packages/docs/docs/zh/plugin/official/plugin-pwa.md
> chore: replace zh-cn

- packages/docs/docs/theme/default-theme-config.md
**Summary**
A simple link replacement to fix 2 dead Algolia DocSearch links
> Fixed dead Algolia DocSearch links

- packages/vuepress/lib/handleUnknownCommand.js
> fix(cli): `.vuepress/config.ts` does not respect custom command (close: #3113)

- packages/@vuepress/types/src/theme-default.ts
> fix(types): missing types for nested sidebar group (close: #3127)

- packages/docs/docs/zh/guide/typescript-as-config.md
> Update typescript-as-config.md for Chinese translation

- README.md
- anchor tag for downloads counter/shield only had closing tag
- added `<a href="#">` at beginning for non-clickable
**Summary**
> fixed broken anchor tag

- packages/@vuepress/markdown/__tests__/__snapshots__/preWrapper.spec.js.snap
- packages/@vuepress/markdown/__tests__/fragments/code-prewrapper-with-double-quotation-marks.md
- packages/@vuepress/markdown/__tests__/preWrapper.spec.js
- packages/@vuepress/markdown/lib/preWrapper.js
> fix(markdown): replace double quotation marks in classname(fix #3152)

- packages/docs/docs/theme/default-theme-config.md
- packages/docs/docs/zh/theme/default-theme-config.md
> fix: Wrong "comma" position in the Algolia configuration sample code

- packages/@vuepress/core/lib/node/theme-api/index.js
> fix(core): failed to resolve theme components when using theme inheritance (close: #3163)
